swagger: '2.0'

info:
  version: 0.0.0
  title: ThingsPro Tenant Portal RESTful API reference
basePath: '/api/v1'
schemes:
  - http
  - https
produces:
  - application/json

tags:
  - name: user

paths:
  /login:
    post:
      description: user login
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              username:
                type: string
                example: 'thingspro@moxa.com'
              password:
                type: string
                example: '12345678'
      responses:
        200:
          description: Return user and token data
          schema:
            $ref: '#/definitions/LoginRes'
            example:
              $ref: '#/externalDocs/x-mocks/LoginRes'
      tags:
        - user

  /logout:
    post:
      description: user logout
      responses:
        200:
          description: user logout
      tags:
        - user

definitions:
  Partner:
    type: object
    properties:
      portalName:
        type: string
        description: Tenant portal name.
      domainName:
        type: string
        description: Tenant domain name.
      supporter:
        type: string
        description: Tenant supporter name.
      supporterEmail:
        type: string
        description: Tenant supporter email.
      createdAt:
        type: string
        description: Tenant created time, ISO data format, like '2018-08-12T20:17:46.384Z'.

  LoginRes:
    type: object
    properties:
      partner:
        type: object
        items:
          - $ref: '#/definitions/Partner'
      user:
        type: object
        items:
          - $ref: '#/definitions/User'
      token:
        type: string
        description: Granted authentication token.

  User:
    type: object
    properties:
      tenantId:
        type: string
        description: Unique identifier representing a specific tenant.
      userId:
        type: string
        description: Unique identifier representing a specific user.
      displayName:
        type: string
        description: Username of user.
      firstName:
        type: string
        description: First name of user.
      lastName:
        type: string
        description: Last name of user.
      avatar:
        type: string
        description: Avatar of user.
      email:
        type: string
        description: Email of user.
      company:
        type: string
        description: Company of user.
      department:
        type: string
        description: Department of user.
      employeeId:
        type: string
        description: Employee Id of user.
      phone:
        type: string
        description: Phone of user.
      status:
        type: string
        description: Enable Status of user.
      data:
        type: object
        description: Metadata of user.
      loginAt:
        type: string
        description: User last login time, ISO data format, like '2018-08-12T20:17:46.384Z'.
      passwordExpireAt:
        type: string
        description: Last change password time, ISO data format, like '2018-08-12T20:17:46.384Z'.
      role:
        type: array
        description: List of role which contains the user.
        items:
          '$ref': '#/definitions/Role'

  Role:
    type: object
    properties:
      id:
        type: integer
        description: Unique identifier representing a specific user.
      name:
        type: string
        description: Name of role.
      description:
        type: string
        description: Description of role.
      admin:
        type: boolean
        description: Admin role.

externalDocs:
  url: 'https://#'
  x-mocks:
    LoginRes:
      {
        "partner":
          {
            "avatar": "https://thingspro9dev4system.blob.core.windows.net/images/avatar/partner/07473967-3c29-4914-b275-d0511c42554e.jpeg",
            "createdAt": "2019-03-12T03:33:17.617015Z",
            "creator": "Cain Chen",
            "data": {},
            "domainName": "partner-dev",
            "financeContact": {
              "avatar": "",
              "displayName": "Kevin Kao",
              "email": "kevincy.kao@moxa.com",
              "phone": "02-89191230",
              "userId": "1378ca4f-392f-48bf-955d-68f3369a4f07"
            },
            "generalContact": {
                "avatar": "",
                "displayName": "Rick Peng",
                "email": "rick.peng@moxa.com",
                "phone": "02-89191230",
                "userId": "a1be69eb-258e-4c66-b07b-583474e57305"
            },
            "supportContact": {
                "avatar": "https://thingspro9dev4system.blob.core.windows.net/images/avatar/user/6df5d905-e19c-4cc8-b963-88707c6fa7f3.jpeg",
                "displayName": "Edie Lin",
                "email": "ediejy.lin@moxa.com",
                "phone": "02-89191230",
                "userId": "6df5d905-e19c-4cc8-b963-88707c6fa7f3"
            },
            "partnerId": "07473967-3c29-4914-b275-d0511c42554e",
            "partnerName": "MOXA Partner",
            "updatedAt": "2019-03-13T08:00:55.150882Z",
            "updater": "Cain Chen"
          },
        "user":
          {
            "avatar": "https://www.moxa.com/80f1.jpg",
            "company": "MOXA Inc.",
            "creator": "Cain Chen",
            "createdAt": "2018-08-12T20:17:46.384Z",
            "data": 
              {
                "CUSTOM_FIELD": "CUSTOM_VALUE"
              },
            "department": "Department",
            "displayName": "Ellen Woods",
            "email": "ellen@moxa.com",
            "employeeId": "123",
            "firstName": "Ellen",
            "lastName": "Woods",
            "partnerId": "07473967-3c29-4914-b275-d0511c42554e",
            "phone": "02-89191230",
            "passwordExpireAt": "2019-01-22T08:02:49:089Z",
            "userId": "916b3c8b-8c61-46a3-8751-e1bc4ddf80f1",
            "role": {
              "id": 1,
              "admin": true,
              "name": "Administrator",
              "description": "Administrator"
            }
          },
        "token": "USER_TOKEN"
      }
