swagger: '2.0'

info:
  version: 0.0.0
  title: ThingsPro Tenant Portal RESTful API reference
basePath: '/api/v1'
schemes:
  - http
  - https
produces:
  - application/json

tags:
  - name: user

paths:
  /login:
    post:
      description: user login
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              username:
                type: string
                example: 'thingspro@moxa.com'
              password:
                type: string
                example: '12345678'
      responses:
        200:
          description: Return user and token data
          schema:
            $ref: '#/definitions/LoginRes'
            example: 
              $ref: '#/externalDocs/x-mocks/LoginRes'
      tags:
        - user

  /logout:
    post:
      description: user logout
      responses:
        200:
          description: user logout
      tags:
        - user

definitions:
  LoginRes:
    type: object
    properties:
      user:
        type: object
      token:
        type: string
        description: Granted authentication token.

externalDocs:
  url: 'https://#'
  x-mocks:
    LoginRes:
      {
        "user":
          {
            "avatar": "https://www.moxa.com/80f1.jpg",
            "company": "MOXA Inc.",
            "createdAt": "2018-08-12T20:17:46.384Z",
            "data": 
              {
                "CUSTOM_FIELD": "CUSTOM_VALUE"
              },
            "department": "Department",
            "displayName": "Ellen Woods",
            "domainName": "partner-dev",
            "email": "ellen@moxa.com",
            "employeeId": "123",
            "firstName": "Ellen",
            "lastName": "Woods",
            "partnerId": "07473967-3c29-4914-b275-d0511c42554e",
            "phone": "02-89191230",
            "portalName": "MOXA Partner",
            "passwordExpireAt": "2019-01-22T08:02:49:089Z",
            "userId": "916b3c8b-8c61-46a3-8751-e1bc4ddf80f1",
            "role": {
              "admin": true,
              "id": 1,
              "name": "Administrator",
              "permission": [
                {
                  "id": 1,
                  "name": "User & Role management",
                  "value": 1
                },
                {
                  "id": 2,
                  "name": "Device register",
                  "value": 1
                },
                {
                  "id": 3,
                  "name": "Device grouping",
                  "value": 1
                },
                {
                  "id": 4,
                  "name": "View device information",
                  "value": 1
                },
                {
                  "id": 5,
                  "name": "Full manage device",
                  "value": 1
                }
              ]
            }
          },
        "token": "USER_TOKEN"
      }
