swagger: '2.0'

info:
  version: 0.0.0
  title: ThingsPro Server RESTful API reference
basePath: '/api/v1'
schemes:
  - http
  - https
produces:
  - application/json
securityDefinitions:
  mx-api-token:
    type: apiKey
    name: mx-api-token
    in: header
    description: ThingsPro RESTful API token, The token should be created on web console.

tags:
  - name: deviceTasks
    description: Remote Task

paths:
  /deviceTasks:
    post:
      tags:
        - deviceTasks
      security:
        - mx-api-token: []
      description: Create a remote task to target device
      consumes:
        - application/json
      parameters:
        - name: body
          in: body
          description: Remote task
          required: true
          schema:
            $ref: '#/definitions/DeviceTaskCreate'
      responses:
        '200':
          description: Response of remote task
          schema:
            $ref: '#/definitions/DeviceTaskResp'
            example:
              $ref: '#/externalDocs/x-mocks/DeviceTaskResp'
    put:
      tags:
        - deviceTasks
      security:
        - mx-api-token: []
      description: >
        Create a remote task (with files) to target device

        Note: This is a pseudo method because OpenAPI 2.0's limitation, please
        use method **POST instead of PUT**.
      consumes:
        - multipart/form-data
      parameters:
        - name: files
          in: formData
          type: file
          description: Upload files with fieldname (files is only for example)
          required: false
        - name: jsonData
          in: formData
          type: string
          description: JSON string of payload
          required: false
      responses:
        '200':
          description: Response of remote task
          schema:
            $ref: '#/definitions/DeviceTaskResp'
            example:
              $ref: '#/externalDocs/x-mocks/DeviceTaskResp'
              
definitions:
  DeviceTaskCreate:
    type: object
    required:
      - deviceUUID
      - payload
    properties:
      deviceUUID:
        description: Target device's uuid
        type: string
      payload:
        type: object
        description: >-
          RESTful Message, for more detail please refer to ThingsPro Gateway
          RESTful Reference
        required:
          - method
          - resource
        properties:
          method:
            description: method of this request message
            type: string
            enum:
              - get
              - post
              - put
              - delete
          resource:
            type: string
            description: resource of this request message
          data:
            description: Body
            allOf:
              - type: array
                description: array data
                items:
                  - type: string
              - type: object
                description: object data
    example:
      $ref: '#/externalDocs/x-mocks/DeviceTaskCreate'

  DeviceTaskResp:
    type: object
    required:
      - taskID
      - code
      - data
      - method
      - resource
      - sign
    properties:
      taskID:
        description: Task ID of this request
        type: string
      code:
        description: status code for this request (like HTTP Status code)
        type: number
      method:
        description: method of this request (like HTTP Method)
        type: string
        enum:
          - get
          - post
          - put
          - delete
      resource:
        description: resource of this request (like HTTP URI)
        type: string
      sign:
        description: Who signed (processed) this message
        type: array
        items:
          type: string
      data:
        description: response data of this request (like HTTP Body)
        type: object
    example:
      $ref: '#/externalDocs/x-mocks/DeviceTaskResp'

externalDocs:
  url: 'http://#'
  x-mocks:
    DeviceTaskCreate:
      deviceUUID: 2730e69e-8d5a-4642-a7cf-966365f991fd
      payload:
        method: get
        resource: /system/services
    DeviceTaskResp:
      taskID: b6723b17-9497-4436-aaa6-fbba5a5d1fd0
      code: 200
      data:
        - enable: true
          id: 1
          name: ssh
          status: true
        - enable: true
          id: 2
          name: rsyslog
          status: true
        - enable: true
          id: 3
          name: mxssdpd
          status: true
      id: 638000
      method: get
      resource: /system/services
      sign:
        - service
