swagger: '2.0'

info:
  version: 0.0.0
  title: ThingsPro Partner Portal RESTful API reference
basePath: '/api/v1'
schemes:
  - http
  - https
produces:
  - application/json
tags:
  - name: offer
    description: Handles offer apply function

paths:
  /offers:
    get:
      description: Get all offer data
      parameters:
        - name: sort
          in: query
          description: Sorting the filter group list, default is desc
          required: false
          type: string
          enum:
          - desc
          - asc
        - name: limit
          in: query
          description: max return groups count (default is 100 and max is 1000)
          required: false
          type: integer
        - name: offset
          in: query
          description: offset
          required: false
          type: integer
      responses:
        200:
          description: An array of apply offer 
          schema:
            type: array
            items:
              $ref: '#/definitions/Offer'
            example: 
              $ref: '#/externalDocs/x-mocks/OfferList'
      tags:
        - offer
    post:
      description: Create a new offer.
      parameters:
        - name: body
          in: body
          description: ''
          required: true
          schema:
            type: object
            items:
              $ref: '#/definitions/OfferCreate'
            example:
              $ref: '#/externalDocs/x-mocks/OfferCreate'    
      responses:
        201:
          description: Create offer successfully
          schema:
            type: object
            items:
              $ref: '#/definitions/Offer'
            example: 
              $ref: '#/externalDocs/x-mocks/Offer'
      tags:
        - offer

definitions:
  Offer:
    type: object
    properties:
      offerId:
        type: integer
        description: Unique identifier representing a specific offer.
      offerName:
        type: string
        description: Name of Offer.
      product:
        type: string
        enum:
        - Standard
        - Professional
        description: Product type of offer.
      duration:
        type: integer
        description: Commit month of offer, should be [0-12], 0 presents infinte.  
      price:
        type: number
        format: float
        description: Price of offer
      deviceLimit:
        type: integer
        description: Limit number of devices
      deviceOverage:
        type: boolean
        description: Device can overage or not.
      deviceOverageRate:
        type: number
        format: float
        description: Price of overage device.
      apiLimit:
        type: integer
        description: Limit number of api  
      apiOverage:
        type: boolean
        description: Api can overage or not.
      apiOverageRate:
        type: number
        format: float
        description: Price of overage api.
      createdAt:
        type: string
        description: Offer created time, ISO data format, like '2018-08-12T20:17:46.384Z'.
   
  OfferCreate:
    type: object
    required:
      - offerName
      - product
      - duration
      - price
      - deviceLimit
      - deviceOverage
      - deviceOverageRate
      - apiLimit
      - apiOverage
      - apiOverageRate
    properties:
      offerName:
        type: string
        description: Name of Offer.
      product:
        type: string
        enum:
        - Standard
        - Professional
        description: Product type of offer.
      duration:
        type: integer
        description: Commit month of offer, should be [0-12], 0 presents infinte.  
      price:
        type: number
        format: float
        description: Price of offer
      deviceLimit:
        type: integer
        description: Limit number of devices
      deviceOverage:
        type: boolean
        description: Device can overage or not.
      deviceOverageRate:
        type: number
        format: float
        description: Price of overage device.
      apiLimit:
        type: integer
        description: Limit number of api  
      apiOverage:
        type: boolean
        description: Api can overage or not.
      apiOverageRate:
        type: number
        format: float
        description: Price of overage api.

externalDocs:
  url: 'http://#'
  x-mocks:
    Offer:
      {
        "offerId": "1",
        "offerName": "65af94c4-07e4-43d7-abad-3cb5f295550b",
        "portalNmae": "MOXA",
        "tenantAvatar": "https://www.moxa.com",
        "mac": "00-0C-29-70-D2-EC", 
        "serialNumber": "12345678", 
        "modelName": "UC-8112",    
        "note": "test device",
        "reason": "",
        "applicant": "Owen Kao",
        "applyAt": "2018-10-01T08:25:31.422Z",
        "applyStatus": "waiting",
        "createdAt": "2018-10-01T08:25:31.422Z"
      }
    OfferList:
      {
        "count": 5,
        "offset": 0,
        "limit": 100,
        "data":
          [
            {
              "id": "1",
              "tenantId": "65af94c4-07e4-43d7-abad-3cb5f295550b",
              "portalNmae": "MOXA",
              "tenantAvatar": "https://www.moxa.com",
              "mac": "00-0C-29-70-D2-EC", 
              "serialNumber": "12345678", 
              "modelName": "UC-8112",    
              "note": "test device",
              "reason": "",
              "applicant": "Owen Kao",
              "applyAt": "2018-10-01T08:25:31.422Z",
              "applyStatus": "waiting",
              "createdAt": "2018-10-01T08:25:31.422Z"
            }
          ]
      }
    OfferCreate:
      {
        "tenantId": "65af94c4-07e4-43d7-abad-3cb5f295550b",
        "mac": "00-0C-29-70-D2-EC", 
        "serialNumber": "12345678",
        "modelName": "UC-8112",  
        "note": "test device"
      }


