swagger: '2.0'

info:
  version: 2.1.0
  title: ThingsPro Gateway RESTful API reference
basePath: '/api/v1'
schemes:
  - http
  - https
produces:
  - application/json
securityDefinitions:
  mx-api-token:
    type: apiKey
    name: mx-api-token
    in: header
    description: ThingsPro RESTful API token, The token should be created on web console.

tags:
  - name: logprofile
    description: Handles log profile configuration

paths:
  '/mxc/logprofile':
    get:
      description: Get Log Profile collection
      parameters:
        - name: destinations
          in: query
          required: false
          type: integer
      responses:
        '200':
          description: success
          schema:
            type: array
            items:
              '$ref': '#/definitions/LogProfile'
            example:
              - id: 1
                name: log-profile-1
                enable: true
                archiver:
                  destination: Internal
                  thresholdBytePerFile: 5242800
                  directorySizeLimitByte: 10240000
                  archivesToKeep: 24
                uploader:
                  httpPost:
                    url: http://host/post
                    enableAuth: false
                    authentication:
                      username: uploader
                      password: password
                    headerList:
                      - name: Content-Type
                        value: application/json
                      - name: User-Agent
                        value: Mozilla/5.0
                    bypassSsl: true
                    cronExpr: 0 * * * *
                    format: json
                    compress: gzip
                    enableCompress: true
                    retryCount: 3
                    retryPeriodSec: 3
                equipmentList:
                  - equipmentName: My-ioLogik-E2242
                    equipmentTags:
                      - name: di0
                        logOnChange: false
                      - name: di1
                        logOnChange: false
                      - name: ai0
                        logOnChange: false
                  - equipmentName: My-other-ioLogik-E2242
                    equipmentTags:
                      - name: di0
                        logOnChange: false
                      - name: di1
                        logOnChange: false
                      - name: ai0
                        logOnChange: false
              - id: 2
                enable: false
                name: log-profile-2
                archiver:
                  destination: Internal
                  thresholdBytePerFile: 5242800
                  directorySizeLimitByte: 10240000
                  archivesToKeep: 24
                uploader:
                  httpPost:
                    url: http://host/post
                    enableAuth: true
                    authentication:
                      username: uploader
                      password: password
                    headerList:
                      - name: Content-Type
                        value: application/json
                      - name: User-Agent
                        value: Mozilla/5.0
                    bypassSsl: true
                    cronExpr: 0 * * * *
                    format: json
                    compress: gzip
                    enableCompress: false
                    retryCount: 3
                    retryPeriodSec: 3
                equipmentList:
                  - equipmentName: My-ioLogik-E2242
                    equipmentTags:
                      - name: di0
                        logOnChange: true
                      - name: di1
                        logOnChange: false
                      - name: ai0
                        logOnChange: true
                  - equipmentName: My-other-ioLogik-E2242
                    equipmentTags:
                      - name: di0
                        logOnChange: true
                      - name: di1
                        logOnChange: true
                      - name: ai0
                        logOnChange: true
        x-query-destinations:
          description: Get logprofile save destination options
          schema:
            type: array
            items:
              '$ref': '#/definitions/DestinationEntry'
            example:
              - name: Internal
                directory: '/var/mxlogariver'
              - name: SD
                directory: '/media'
      tags:
        - logprofile
      security:
        - mx-api-token: []
    post:
      description: Create a Log Profile
      parameters:
        - name: body
          in: body
          required: true
          schema:
            '$ref': '#/definitions/LogProfile'
      responses:
        '200':
          description: success
          schema:
            '$ref': '#/definitions/LogProfile'
            example:
              id: 1
              name: log-profile-1
              enable: true
              archiver:
                destination: Internal
                thresholdBytePerFile: 5242800
                directorySizeLimitByte: 10240000
                archivesToKeep: 24
              uploader:
                httpPost:
                  url: http://host/post
                  enableAuth: false
                  authentication:
                    username: uploader
                    password: password
                  headerList:
                    - name: Content-Type
                      value: application/json
                    - name: User-Agent
                      value: Mozilla/5.0
                  bypassSsl: true
                  cronExpr: 0 * * * *
                  format: json
                  compress: gzip
                  enableCompress: true
                  retryCount: 3
                  retryPeriodSec: 3
              equipmentList:
                - equipmentName: My-ioLogik-E2242
                  equipmentTags:
                    - name: di0
                      logOnChange: false
                    - name: di1
                      logOnChange: false
                    - name: ai0
                      logOnChange: false
                - equipmentName: My-other-ioLogik-E2242
                  equipmentTags:
                    - name: di0
                      logOnChange: false
                    - name: di1
                      logOnChange: false
                    - name: ai0
                      logOnChange: false
      tags:
        - logprofile
      security:
        - mx-api-token: []
  '/mxc/logprofile/{id}':
    parameters:
      - name: id
        in: path
        type: integer
        required: true
    delete:
      description: Delete a Log Profile with assigned ID
      responses:
        '200':
          description: success
      tags:
        - logprofile
      security:
        - mx-api-token: []
    put:
      description: Update a Log Profile with assigned ID
      parameters:
        - name: body
          in: body
          required: true
          schema:
            '$ref': '#/definitions/LogProfile'
      responses:
        '200':
          description: success
          schema:
            '$ref': '#/definitions/LogProfile'
            example:
              id: 1
              name: log-profile-1
              enable: true
              archiver:
                destination: Internal
                thresholdBytePerFile: 5242800
                directorySizeLimitByte: 10240000
                archivesToKeep: 24
              uploader:
                httpPost:
                  url: http://host/post
                  enableAuth: false
                  authentication:
                    username: uploader
                    password: password
                  headerList:
                    - name: Content-Type
                      value: application/json
                    - name: User-Agent
                      value: Mozilla/5.0
                  bypassSsl: true
                  cronExpr: 0 * * * *
                  format: json
                  compress: gzip
                  enableCompress: true
                  retryCount: 3
                  retryPeriodSec: 3
              equipmentList:
                - equipmentName: My-ioLogik-E2242
                  equipmentTags:
                    - name: di0
                      logOnChange: false
                    - name: di1
                      logOnChange: false
                    - name: ai0
                      logOnChange: false
                - equipmentName: My-other-ioLogik-E2242
                  equipmentTags:
                    - name: di0
                      logOnChange: false
                    - name: di1
                      logOnChange: false
                    - name: ai0
                      logOnChange: false
      tags:
        - logprofile
      security:
        - mx-api-token: []
  '/mxc/equipments':
    get:
      description: Get all equipment tags. If equipment name conflicts, it will merged
        into one tag and concat description with ";"
      responses:
        '200':
          description: success
          schema:
            type: array
            items:
              '$ref': '#/definitions/LogListEquipment'
            example:
              - equipmentType: modbus
                equipmentName: My-other-ioLogik-E2242
                equipmentTags:
                  - name: di0
                    dataType: boolean
                    access: ro
                    size: 1
                    description: di0
                    function: read-discrete-inputs
                    address: 0
                    quantity: 1
                  - name: di1
                    dataType: boolean
                    access: ro
                    size: 1
                    description: di1
                    function: read-discrete-inputs
                    address: 1
                    quantity: 1
                  - name: ai0
                    dataType: uint16
                    access: ro
                    size: 2
                    description: ai0
                    function: read-holding-registers
                    address: 0
                    quantity: 1
              - equipmentType: user
                equipmentName: program-1
                equipmentTags:
                  - name: cpu
                    dataType: float32
                    access: ro
                    size: 4
                    description: CPU Usage (%)
                  - name: memory
                    dataType: float32
                    access: ro
                    size: 4
                    description: Memory Usage (%)
                  - name: abc
                    dataType: string
                    access: ro
                    size: 4
                    description: def
      tags:
        - logprofile
      security:
        - mx-api-token: []

definitions:
  LogProfile:
    title: LogProfile
    required:
      - name
      - archiver
      - uploader
      - equipmentList
    properties:
      id:
        type: integer
        readOnly: true
      enable:
        type: boolean
        description: Enable Log Profile
        default: true
      name:
        type: string
        description: Name of Log Profile
        pattern: '^[A-Za-z0-9_-]+$'
        minLength: 2
        maxLength: 255
      archiver:
        '$ref': '#/definitions/Archiver'
      uploader:
        '$ref': '#/definitions/Uploader'
      equipmentList:
        type: array
        description: Collection of equipments using current Log Profile
        items:
          '$ref': '#/definitions/LogEquipmentEntry'
    example:
      id: 1
      name: log-profile-1
      enable: true
      archiver:
        destination: Internal
        thresholdBytePerFile: 5242800
        directorySizeLimitByte: 10240000
        archivesToKeep: 24
      uploader:
        httpPost:
          url: http://host/post
          enableAuth: false
          authentication:
            username: uploader
            password: password
          headerList:
            - name: Content-Type
              value: application/json
            - name: User-Agent
              value: Mozilla/5.0
          bypassSsl: true
          cronExpr: 0 * * * *
          format: json
          compress: gzip
          enableCompress: true
          retryCount: 3
          retryPeriodSec: 3
      equipmentList:
        - equipmentName: My-ioLogik-E2242
          equipmentTags:
            - name: di0
              logOnChange: false
            - name: di1
              logOnChange: false
            - name: ai0
              logOnChange: false
        - equipmentName: My-other-ioLogik-E2242
          equipmentTags:
            - name: di0
              logOnChange: false
            - name: di1
              logOnChange: false
            - name: ai0
              logOnChange: false
  Archiver:
    title: Archiver
    type: object
    description: Archiver Options for Log Profile
    required:
      - destination
      - thresholdBytePerFile
      - directorySizeLimitByte
      - archivesToKeep
    properties:
      destination:
        description: Archive files' place, refer to "/mxc/logprofile/destination:name"
        type: string
      thresholdBytePerFile:
        description: Maximum size of an archive file (byte)
        type: integer
        minimum: 1048576
      directorySizeLimitByte:
        description: Maximum archive folder size (byte)
        type: integer
        minimum: 10240
      archivesToKeep:
        description: Maximum count of archive files
        type: integer
        minimum: 1
        maximum: 1000
  DestinationEntry:
    title: DestinationEntry
    description: Archive files' place could be set to
    type: object
    required:
      - name
      - directory
    properties:
      name:
        description: destination name
        type: string
      directory:
        description: Archive files' path
        type: string
  Uploader:
    title: Uploader
    description: Uploader Options for Log Profile
    type: object
    required:
      - httpPost
    properties:
      httpPost:
        type: object
        required:
          - url
          - enableAuth
          - authentication
          - bypassSsl
          - cronExpr
          - format
          - compress
          - enableCompress
          - retryCount
          - retryPeriodSec
        properties:
          url:
            description: Upload url
            type: string
          enableAuth:
            description: Enable HTTP Basic Authication
            type: boolean
          authentication:
            type: object
            required:
              - username
              - password
            properties:
              username:
                description: Username for HTTP Basic Authication
                type: string
              password:
                description: Password of HTTP Basic Authication
                type: string
          headerList:
            description: HTTP/HTTPS headers list
            type: array
            items:
              type: object
              required:
                - name
                - value
              properties:
                name:
                  description: Name of headers
                  type: string
                value:
                  description: Value of headers
                  type: string
          bypassSsl:
            description: Bypass SSL certificate
            type: boolean
          cronExpr:
            description: Schedule upload (use cron format)
            type: string
          format:
            description: 'Type of upload file format (supports: json, csv, xml)'
            type: string
            enum:
              - json
              - csv
              - xml
          compress:
            description: 'Compress Algorithm (supports: gzip)'
            type: string
            enum:
              - gzip
          enableCompress:
            description: Enable compress
            type: boolean
          retryCount:
            description: Upload retry count
            type: integer
          retryPeriodSec:
            description: Upload retry period (seconds)
            type: integer
  LogEquipmentEntry:
    title: Equipment Entry
    description: Device Tags Options for Log Profile
    type: object
    required:
      - equipmentName
      - equipmentTags
    properties:
      equipmentName:
        description: Name of equipment
        type: string
      equipmentTags:
        description: Equipment Tags List
        type: array
        items:
          type: object
          required:
            - name
            - logOnChange
          properties:
            name:
              description: Name of tag
              type: string
            logOnChange:
              description: Enable log on change
              type: boolean
  LogListEquipment:
    title: Equipment
    description: Equipment object
    type: object
    required:
      - equipmentType
      - equipmentName
      - equipmentTags
    properties:
      equipmentType:
        description: Type of equipment
        type: string
        enum:
          - modbus
          - user
          - system
      equipmentName:
        description: Name of equipment
        type: string
        minLength: 1
        maxLength: 255
      equipmentTags:
        description: Tag List of equipment
        type: array
        items:
          '$ref': '#/definitions/LogListEquipmentTag'
  LogListEquipmentTag:
    title: Tag
    description: Equipment's tag entry
    type: object
    required:
      - name
      - dataType
      - access
      - size
      - description
    properties:
      name:
        description: Name of tag
        type: string
        minLength: 1
        maxLength: 255
      dataType:
        description: Data type of tag
        type: string
        enum:
          - boolean
          - uint16
          - uint32
          - uint64
          - int16
          - int32
          - int64
          - float32
          - float64
          - string
          - bytearray
      access:
        description: Access type of tag
        type: string
        enum:
          - ro
          - wo
          - rw
      size:
        description: Size of tag in byte
        type: integer
      description:
        description: Description of tag
        type: string
        minLength: 0
        maxLength: 4096
