language: node_js
node_js:
  - 'node'
cache:
  yarn: true
  directories:
    - node_modules
env:
  - PACKAGE=gateway
  - PACKAGE=server
  - PACKAGE=edge
  - PACKAGE=tenant-portal
  - PACKAGE=admin-portal
script: yarn lint $PACKAGE
