swagger: '2.0'

info:
  version: 0.0.8
  title: ThingsPro Tenant Portal RESTful API reference
  description: |
    Welcome to the ThingsPro Tenant Portal RESTful API reference. This is a live document of how you can use ThingsPro Gateway APIs.
    The ThingsPro Gateway API is organized around the [REST](https://en.wikipedia.org/wiki/Representational_state_transfer) methodology, and it uses resource-oriented URLs, and common HTTP response codes to indicate API errors.

host: localhost
basePath: '/api/v1'

schemes:
  - http
  - https

produces:
  - application/json

securityDefinitions:
  token:
    type: apiKey
    name: Authorization
    in: header
    description: Authenicate token, format should be 'Bearer XXXXXX' in your header

tags:
  - $ref: './user/index.yaml#/tags'
  - $ref: './device/index.yaml#/tags'
  - $ref: './edgeapp/index.yaml#/tags'
  - $ref: './order/index.yaml#/tags'
  - $ref: './cert/index.yaml#/tags'  
  - $ref: './tenant/index.yaml#/tags'

paths:
  - $ref: './user/index.yaml#/paths'
  - $ref: './device/index.yaml#/paths'
  - $ref: './edgeapp/index.yaml#/paths'
  - $ref: './order/index.yaml#/paths'
  - $ref: './cert/index.yaml#/paths'
  - $ref: './tenant/index.yaml#/paths'

definitions:
  - $ref: './user/index.yaml#/definitions'
  - $ref: './device/index.yaml#/definitions'
  - $ref: './edgeapp/index.yaml#/definitions'
  - $ref: './order/index.yaml#/definitions'
  - $ref: './cert/index.yaml#/definitions'
  - $ref: './tenant/index.yaml#/definitions'  