swagger: '2.0'

info:
  version: 2.1.0
  title: ThingsPro Gateway RESTful API reference
basePath: '/api/v1'
schemes:
  - http
  - https
produces:
  - application/json
securityDefinitions:
  mx-api-token:
    type: apiKey
    name: mx-api-token
    in: header
    description: ThingsPro RESTful API token, The token should be created on web console.

tags:
  - name: firmware
    description: Manages the firmware upgrade function

paths:
  '/system/firmware':
    post:
      description: Upgrade firmware by given url
      parameters:
        - name: body
          in: body
          required: true
          schema:
            '$ref': '#/definitions/FirmwareInfo'
      responses:
        '200':
          description: success
      tags:
        - firmware
      security:
        - mx-api-token: []

definitions:
  FirmwareInfo:
    description: Firmware Info
    type: object
    required:
      - file
    properties:
      delay:
        description: Delay time in seconds before execute the upgrading process
        type: integer
      file:
        description: Remote firmware meta data
        type: object
        required:
          - url
          - physicalPath
        properties:
          url:
            description: URL for downloading firmware
            type: string
            minLength: 1
            maxLength: 4096
          physicalPath:
            description: File's physical path on machine
            type: string
            minLength: 1
            maxLength: 4096
          headers:
            description: Headers for downloading firmware if necessary
            type: object
    example:
      delay: 3
      file:
        url: http://192.168.31.81:5000/api/v1/download/1234
        headers:
          accessToken: MOXAMOXA-TEST-SYSTEM
