swagger: '2.0'

info:
  version: 0.0.1
  title: ThingsPro Tenant Portal RESTful API reference
basePath: '/api/v1'
schemes:
  - http
  - https
produces:
  - application/json
tags:
  - name: edgeapp
    description: Handles edge app data

paths:
  /edgeapp:
    get:
      parameters:
        - name: appName
          in: query
          description: Filter the edge app list by appName
          required: false
          type: string
        - name: cpuArch
          in: query
          description: Filter the edge app list by cpuArch
          required: false
          type: string
        - name: categoryId
          in: query
          description: Filter the edge app list by categoryId
          required: false
          type: string
        - name: categoryName
          in: query
          description: Filter the edge app list by categoryName
          required: false
          type: string
        - name: order
          in: query
          description: Ordering the filter edge app list, default is asc
          required: false
          type: string  
          enum:
          - desc
          - asc
        - name: sort
          in: query
          description: Sort the edge app list by specific ordering, default is sort by 'appId'
          required: false
          type: string
          enum:
          - appId
          - appName
          - categoryId
          - categoryName
        - name: limit
          in: query
          description: max return edge app count (default is 100 and max is 1000)
          required: false
          type: integer  
        - name: offset
          in: query
          description: offset
          required: false
          type: integer             
      description: Get all edge app field data
      responses:
        200:
          description: An array of edge app
          schema:
            type: array
            items:
              $ref: '#/definitions/EdgeApp'
          examples: { 'application/json': { $ref: '#/externalDocs/x-mocks/EdgeAppList' } }
      tags:
        - edgeapp

  /edgeapp/{id}:
    parameters:
      - name: id
        in: path
        description: edge app version id
        required: true
        type: string
    get:
      description: Return edge app data & version info with given ID
      tags:
        - edgeapp
      responses:
        200:
          description: An Object of the edge app
          schema:
            type: object
            items:
              $ref: '#/definitions/EdgeApp'
          examples: { 'application/json': { $ref: '#/externalDocs/x-mocks/EdgeApp' } }

  /edgeapp/appId/{appId}:
    parameters:
      - name: appId
        in: path
        description: edge app unique identifier
        required: true
        type: string
    get:
      description: Return edge app data with given ID
      tags:
        - edgeapp
      responses:
        200:
          description: An Object of the edge app
          schema:
            type: object
            items:
              $ref: '#/definitions/EdgeApp'
          examples: { 'application/json': { $ref: '#/externalDocs/x-mocks/EdgeApp' } }

  /edgeapp/category:
    get:
      description: Get all category of edge app
      responses:
        200:
          description: An array of edge app category
          schema:
            type: array
            items:
              $ref: '#/definitions/EdgeAppCategory'
          examples: { 'application/json': { $ref: '#/externalDocs/x-mocks/EdgeAppCategoryList' } }
      tags:
        - edgeapp

definitions:
  EdgeApp:
    type: object
    properties:
      appId:
        type: string
        description: Unique identifier representing a specific edge app.
      appName:
        type: string
        description: Name of edge app.
      cpuArch:
        type: string
        description: CPU Architecture.  
      description:
        type: string
        description: Description of edge app.  
      displayName:
        type: string
        description: Display Name of edge app.
      iconUrl:
        type: string
        description: The icon URL of edge app.
      downloadUrl:
        type: string
        description: The download URL of edge app.
      isTrialLicense:
        type: boolean
        description: Is trial license ?
      licenseStatement:
        type: string
        description: License Statement. ( e.g. Trial - 30 days )
      publishAt:
        type: string
        description: Edge app publist time, ISO data format, like '2018-08-12T20:17:46.384Z'.
      publisher:
        type: string
        description: Publisher of edge app.
      trialPeriodInDay:
        type: string
        description: unknown.
      unitPrice:
        type: number
        description: Unit price of edge app.
      validAt:
        type: string
        description: Edge app valid time, ISO data format, like '2018-08-12T20:17:46.384Z'.
      version:
        type: string
        description: Edge app versoin.
      categoryList:
        type: array
        items:
          type: object
        description: Category ID.

  EdgeAppCategory:
    type: object
    properties:
      categoryId:
        type: integer
        description: Unique identifier representing a specific edge app category.
      categoryName:
        type: string
        description: Name of edge app category.
      description:
        type: integer
        description: Description of edge app category.  

externalDocs:
  url: 'http://#'
  x-mocks:
    EdgeApp:
      {
        "appId": 1,
        "appVersionId": 21,
        "appName": "app-azure",
        "categoryList": [
          {
            "categoryId": 3,
            "categoryName": "Edge Intelligence",
            "description": "Edge Intelligence"
          }
        ],
        "cpuArch": "armhf",
        "description": "app-azure",
        "displayName": "app-azure",
        "iconUrl": "http://tenant-west-us.thingspro.io/images/edge-application/app-azure/0.3.0-18/logo.png",
        "downloadUrl": "http://repo.moxa.online/static/v3/edge/builds/edge-app-azure/18/app-azure_0.3.0-18_armhf.mpkg",
        "isTrialLicense": true,
        "licenseStatement": "Trial - 30 days",
        "publishAt": "2018-09-27T06:54:14.203998+00:00Z",
        "publisher": "Moxa-ISD",
        "trialPeriodInDay": null,
        "unitPrice": null,
        "validAt": "2018-09-27T06:54:14.203998+00:00Z",
        "version": "0.3.0-18"
      }
    EdgeAppList:
      {
        "count": 5,
        "offset": 0,
        "limit": 100,
        "data": [
          {
            "appId": 1,
            "appName": "app-azure",
            "appVersionId": 1,
            "categoryList": [
              {
                "categoryId": 2,
                "categoryName": "Cloud Connectivity",
                "description": "Cloud Connectivity"
              }
            ],
            "cpuArch": "amd64",
            "description": "MOXA Azure client",
            "displayName": "Azure Client",
            "downloadUrl": "http://repo.moxa.online/static/v3/edge/builds/edge-app-azure/24/app-azure_0.5.0-24_amd64.mpkg",
            "iconUrl": "http://tenant-west-us.thingspro.io/images/edge-application/app-azure/0.5.0-24/logo.png",
            "isTrialLicense": true,
            "licenseStatement": "Trial - 30 days",
            "publishAt": "2018-09-27T06:53:51.719756+00:00Z",
            "publisher": "Moxa-ISD",
            "trialPeriodInDay": null,
            "unitPrice": null,
            "validAt": "2018-09-27T06:53:51.719756+00:00Z",
            "version": "0.5.0-24"
          },
          {
            "appId": 4,
            "appName": "linuxdesktop",
            "appVersionId": 21,
            "categoryList": [
              {
                "categoryId": 3,
                "categoryName": "Edge Intelligence",
                "description": "Edge Intelligence"
              }
            ],
            "cpuArch": "amd64",
            "description": "Linux Desktop",
            "displayName": "Linux Desktop",
            "downloadUrl": "http://repo.moxa.online/static/v3/edge/builds/edge-app-linuxdesktop/12/linuxdesktop_0.3.0-12_amd64.mpkg",
            "iconUrl": "http://tenant-west-us.thingspro.io/images/edge-application/linuxdesktop/0.3.0-12/logo.png",
            "isTrialLicense": null,
            "licenseStatement": "Trial - 30 days",
            "publishAt": "2018-10-16T06:22:04.373362+00:00Z",
            "publisher": "Moxa-ISD",
            "trialPeriodInDay": null,
            "unitPrice": null,
            "validAt": "2018-10-16T06:22:04.373362+00:00Z",
            "version": "0.3.0-12"
          },
        ]
      }
    EdgeAppCategoryList:
      [
        {
          "categoryId": 1,
          "categoryName": "Protocol",
          "description": "Protocol"
        },
        {
          "categoryId": 2,
          "categoryName": "Cloud Connectivity",
          "description": "Cloud Connectivity"
        },
        {
          "categoryId": 3,
          "categoryName": "Edge Intelligence",
          "description": "Edge Intelligence"
        },
        {
          "categoryId": 4,
          "categoryName": "Others",
          "description": "Others"
        }
      ]
