swagger: '2.0'

info:
  version: 0.0.0
  title: ThingsPro PIC service RESTful API reference
basePath: '/api/v1'
schemes:
  - http
  - https
produces:
  - application/json
tags:
  - name: customer
    description: Handle customers data

paths:
  /customers:
    get:
      description: Get all customers data
      tags:
        - customer
      parameters:
        - name: displayName
          in: query
          description: Filter the customer list by customer display name
          required: false
          type: string 
        - name: order
          in: query
          description: The customer list order by some keyword. default is order by 'customer name'
          required: false
          type: string
          enum:
          - name
        - name: sort
          in: query
          description: Sorting the filter customer list, default is asc
          required: false
          type: string
          enum:
          - desc
          - asc
        - name: limit
          in: query
          description: max return customers count (default is 100 and max is 1000)
          required: false
          type: integer
        - name: offset
          in: query
          description: offset
          required: false
          type: integer
      responses:
        200:
          description: An array of customers
          schema:
            type: array
            items:
              $ref: '#/definitions/Customer'
            example:
              $ref: '#/externalDocs/x-mocks/CustomerList'
    post:
      description: Create a new customer.
      tags:
        - customer
      parameters:
        - name: body
          in: body
          description: ''
          required: true
          schema:
            $ref: '#/definitions/CustomerCreate'
      responses:
        201:
          description: Create customer successfully
          schema:
            type: object
            items:
              $ref: '#/definitions/Customer'
            example:
              $ref: '#/externalDocs/x-mocks/Customer'
    put:
      description: Update a new customer.
      tags:
        - customer
      parameters:
        - name: body
          in: body
          description: ''
          required: true
          schema:
            $ref: '#/definitions/CustomerUpdate'
      responses:
        200:
          description: Update customer successfully
          schema:
            type: object
            items:
              $ref: '#/definitions/Customer'
            example:
              $ref: '#/externalDocs/x-mocks/Customer'
definitions:
  Customer:
    type: object
    properties:
      id:
        type: integer
        description: Customer id.
      displayName:
        type: string
        description: Customer name.
      firstName:
        type: string
        description: First name of customer.
      lastName:
        type: string
        description: Last name of customer.
      email:
        type: string
        description: Customer email.
      phone:
        type: string
        description: Phone of customer.
      country:
        type: string
        description: Country of customer.
      channel:
        type: string
        description: Channel distributor of customer.

  CustomerCreate:
    type: object
    required:
    - displayName
    - email
    properties:
      displayName:
        type: string
        description: Customer name.
      firstName:
        type: string
        description: First name of customer.
      lastName:
        type: string
        description: Last name of customer.
      email:
        type: string
        description: Customer email.
      phone:
        type: string
        description: Phone of customer.
      country:
        type: string
        description: Country of customer.
      channel:
        type: string
        description: Channel distributor of customer.

  CustomerUpdate:
    type: object
    properties:
      displayName:
        type: string
        description: Customer name.
      firstName:
        type: string
        description: First name of customer.
      lastName:
        type: string
        description: Last name of customer.
      email:
        type: string
        description: Customer email.
      phone:
        type: string
        description: Phone of customer.
      country:
        type: string
        description: Country of customer.
      channel:
        type: string
        description: Channel distributor of customer.

externalDocs:
  url: 'http://#'
  x-mocks:
    Customer:
      {
        "id": 1,
        "displayName": "moxa",
        "email": "moxa@moxa.com",
        "firstName": "firstName",
        "lastName": "lastName",
        "phone": "1234567890",                      
        "country": "Taiwan",
        "channel": "moxa"
      }
    CustomerCreate:
      {
        "displayName": "moxa",
        "email": "moxa@moxa.com",
        "firstName": "firstName",
        "lastName": "lastName",
        "phone": "1234567890",                      
        "country": "Taiwan",
        "channel": "moxa"
      }
    CustomerUpdate:
      {
        "displayName": "moxa",
        "email": "moxa@moxa.com",
        "firstName": "firstName",
        "lastName": "lastName",
        "phone": "1234567890",                      
        "country": "Taiwan",
        "channel": "moxa"
      }
    CustomerList:
      {
        "count": 28,
        "data": [
          {
            "id": 1,
            "displayName": "moxa",
            "email": "moxa@moxa.com",
            "firstName": "firstName",
            "lastName": "lastName",
            "phone": "1234567890",                      
            "country": "Taiwan",
            "channel": "moxa"
          }
        ],
        "limit": 100,
        "offset": 20
      }

    