swagger: '2.0'

info:
  version: 0.0.0
  title: DLM Company Portal RESTful API reference
basePath: '/api/v1'
schemes:
  - http
  - https
produces:
  - application/json
tags:
  - name: package
    description: Handles packages data

paths:
  /packages:
    get:
      description: Get all packages
      tags:
        - package
      parameters:
        - name: cpuArch
          in: query
          description: Filter the package list by cpu architecture
          required: false
          type: string
        - name: order
          in: query
          description: The package list order by some keyword. default is order by 'createdAt'
          required: false
          type: string
        - name: sort
          in: query
          description: Sorting the filter package list, default is asc
          required: false
          type: string
          enum:
          - desc
          - asc
        - name: limit
          in: query
          description: max return packages count (default is 100 and max is 1000)
          required: false
          type: integer
        - name: offset
          in: query
          description: offset
          required: false
          type: integer
      responses:
        200:
          description: An array of packages
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: '#/definitions/Package'
              count:
                type: integer
              offset:
                type: integer
              limit:
                type: integer
            example:
              $ref: '#/externalDocs/x-mocks/PackageList'

  /packages/{id}:
    parameters:
      - name: id
        in: path
        description: package unique identifier
        required: true
        type: string
    get:
      description: Return package data with given ID
      tags:
        - package
      responses:
        200:
          description: An Object of the package
          schema:
            type: object
            items:
              $ref: '#/definitions/PackageResult'
            example:
              $ref: '#/externalDocs/x-mocks/PackageResult'

definitions:
  Package:
    type: object
    properties:
      id:
        type: integer
        description: Unique identifier representing a specific package.
      packageId:
        type: integer
        description: package id.
      packageName:
        type: string
        description: package name.
      displayName:
        type: string
        description: display name of package.
      description:
        type: string
        description: description of package.
      publisher:
        type: string
        description: publisher of package.
      cpuArch:
        type: string
        description: CPU architecture of package.
      downloadUrl:
        type: string
        description: download URL of package.
      iconUrl:
        type: string
        description: icon URL of package.
      enable:
        type: boolean
        description: enable package or not.
      models:
        type: array
        description: model list of package.
        items:
          type: string
      size:
        type: integer
        description: size of package.
      createdAt:
        type: string
        description: package created time, ISO data format, like '2018-08-12T20:17:46.384Z'.
      updatedAt:
        type: string
        description: package updated time, ISO data format, like '2018-08-12T20:17:46.384Z'.
  PackageResult:
    type: object
    properties:
      data:
        type: object
        items:
          $ref: '#/definitions/Package'

externalDocs:
  url: 'http://#'
  x-mocks:
    Package:
      {
        "id": 3,
        "packageId": 2,
        "packageName": "app-aws",
        "displayName": "AWS Client",
        "description": "MOXA AWS client",
        "publisher": "Moxa",
        "cpuArch": "armhf",
        "downloadUrl": "https://dlm-storage-dev.s3-us-west-2.amazonaws.com/package/edge-app-aws/app-aws_0.12.0-35_armhf.mpkg",
        "iconUrl": "https://dlm-storage-dev.s3-us-west-2.amazonaws.com/package/edge-app-aws/app-aws_0.12.0-35_armhf.png",
        "enable": true,
        "models": [],
        "size": 67832320,
        "version": "0.12.0-35",
        "createdAt": "2019-10-14T03:56:22.015745Z",
        "updatedAt": ""
      }
    PackageResult:
      {
        "data": {
          "id": 3,
          "packageId": 2,
          "packageName": "app-aws",
          "displayName": "AWS Client",
          "description": "MOXA AWS client",
          "publisher": "Moxa",
          "cpuArch": "armhf",
          "downloadUrl": "https://dlm-storage-dev.s3-us-west-2.amazonaws.com/package/edge-app-aws/app-aws_0.12.0-35_armhf.mpkg",
          "iconUrl": "https://dlm-storage-dev.s3-us-west-2.amazonaws.com/package/edge-app-aws/app-aws_0.12.0-35_armhf.png",
          "enable": true,
          "models": [],
          "size": 67832320,
          "version": "0.12.0-35",
          "createdAt": "2019-10-14T03:56:22.015745Z",
          "updatedAt": ""
        }
      }
    PackageList:
      {
        "count": 1,
        "data": [
          {
            "id": 3,
            "packageId": 2,
            "packageName": "app-aws",
            "displayName": "AWS Client",
            "description": "MOXA AWS client",
            "publisher": "Moxa",
            "cpuArch": "armhf",
            "downloadUrl": "https://dlm-storage-dev.s3-us-west-2.amazonaws.com/package/edge-app-aws/app-aws_0.12.0-35_armhf.mpkg",
            "iconUrl": "https://dlm-storage-dev.s3-us-west-2.amazonaws.com/package/edge-app-aws/app-aws_0.12.0-35_armhf.png",
            "enable": true,
            "models": [],
            "size": 67832320,
            "version": "0.12.0-35",
            "createdAt": "2019-10-14T03:56:22.015745Z",
            "updatedAt": ""
          }
        ],
        "limit": 1,
        "offset": 0
      }
