swagger: '2.0'

info:
  version: 0.0.0
  title: ThingsPro Server RESTful API reference
basePath: '/api/v1'
schemes:
  - http
  - https
produces:
  - application/json
securityDefinitions:
  mx-api-token:
    type: apiKey
    name: mx-api-token
    in: header
    description: ThingsPro RESTful API token, The token should be created on web console.

tags:
  - name: groupTasks
    description: Remote Task

paths:
  /groupTasks:
    post:
      description: Create a new group task.
      tags:
      - groupTasks
      parameters:
      - name: body
        in: body
        description: Group Task object
        required: true
        schema:
          $ref: '#/definitions/GroupTaskCreate'
      responses:
        200:
          description: Group Task object
          schema:
            $ref: '#/definitions/GroupTask'
          examples:
            {
              "application/json": {
                $ref: '#/externalDocs/x-mocks/GroupTask'
              }
            }

definitions:
  GroupTask:
    type: array
    description: Array of DeviceTask objects belong to this group.
    items:
      $ref: '#/definitions/DeviceTaskCreate'
  GroupTaskCreate:
    allOf:
    - type: object
      description: Create group task
      properties:
        groupId:
          type: number
          description: ID of group
    - $ref: '#/definitions/DeviceTaskCreate'
    example:
      $ref: '#/externalDocs/x-mocks/GroupTaskCreate'

externalDocs:
  url: 'http://#'
  x-mocks:
    GroupTask:
      {
        "id": 1,
        "name": "Group Name Here",
        "description": "Group Description",
        "deviceStatus": {
          "created": 1,
          "offline": 0,
          "online": 0
        },
        "devices": [
          {
            "connection": {
              "createdAt": "2016-12-22T10:07:56",
              "deviceUUID": "17dbee9c-696c-4598-b1d9-547e740d94fa",
              "status": "created"
            },
            "createdAt": "2016-12-22T10:07:56",
            "description": "Device",
            "displayName": "MOXA HQ Sensor 4",
            "mac": "223344FF8F12",
            "serialNumber": "TAFLB1003683",
            "properties": {},
            "psk": "efe8d947a9a97792e67de8d9137b9a398a40367f30fecb8cdfde9685677dd134",
            "updatedAt": "2016-12-22T10:07:56",
            "uuid": "17dbee9c-696c-4598-b1d9-547e740d94fa"
          }
        ],
        "taskStatus": {
          "completedCount": 1,
          "activeCount": 0,
          "revokedCount": 1,
          "totalCount": 1
        },
        "tasks": [
          {
            "applyPolicy": "none",
            "createdAt": "2017-02-23T08:05:22.003420",
            "deviceUUID": "17dbee9c-696c-4598-b1d9-547e740d94fa",
            "groupTaskUUID": "b801b523-2900-493e-927e-70724c6ed162",
            "retryTimes": 0,
            "revoked": false,
            "scheduledDateTime": "",
            "state": "SUCCESS",
            "success": true,
            "updatedAt": "2017-02-23T08:05:22.003420",
            "uuid": "c3d4e60e-3519-4819-9051-8efbc1d700f1"
          }
        ],
        "createdAt": "2016-12-22T10:08:18",
        "updatedAt": "2016-12-22T10:08:18"
      }
    GroupTaskCreate:
      {
        "groupId": 1,
        "payload": {
          "resource": "/system/reboot",
          "method": "post",
          "data": {}
        },
        "applyPolicy": "none",
        "retryTimes": 0,
        "scheduledDateTime": "2017-01-09T06:46:01.181Z"
      }