swagger: '2.0'

info:
  version: 0.0.1
  title: ThingsPro Tenant Portal RESTful API reference
basePath: '/api/v1'
schemes:
  - http
  - https
produces:
  - application/json
tags:
  - name: order
    description: Handles poc order data

paths:
  /orders:
    get:
      parameters:
        - name: orderId
          in: query
          description: Filter the order list by orderId
          required: false
          type: number
        - name: orderNo
          in: query
          description: Filter the order list by orderNo
          required: false
          type: string
        - name: modelName
          in: query
          description: Filter the order list by modelName
          required: false
          type: string
        - name: creator
          in: query
          description: Filter the order list by creator
          required: false
          type: string
        - name: startDate
          in: query
          description: Filter the order list by start date
          required: false
          type: string
        - name: endDate
          in: query
          description: Filter the order list by end date
          required: false
          type: string
        - name: order
          in: query
          description: Ordering the filter order list, default is asc
          required: false
          type: string
          enum:
          - desc
          - asc
        - name: sort
          in: query
          description: Sort the order list by specific ordering, default is sort by 'createdAt'
          required: false
          type: string
          enum:
          - orderId
          - modelName
          - creator
          - createdAt
        - name: limit
          in: query
          description: max return orders count (default is 100 and max is 1000)
          required: false
          type: integer
        - name: offset
          in: query
          description: offset
          required: false
          type: integer
        - name: distinct
          in: query
          description: Get distict value of speific field, this query parameter will return string array only
          required: false
          type: string
          enum:
          - modelName
          - creator
      description: Get all orders field data
      responses:
        200:
          description: An array of orders
          schema:
            type: array
            items:
              $ref: '#/definitions/Order'
          examples: { 'application/json': { $ref: '#/externalDocs/x-mocks/OrderList' } }
      tags:
        - order
    post:
      description: Create a new poc order.
      parameters:
        - name: body
          in: body
          description: ''
          required: true
          schema:
            $ref: '#/definitions/CreateOrder'
      responses:
        201:
          description: Create a new poc order successfully
          schema:
            type: object
            items:
              $ref: '#/definitions/Order'
          examples: { 'application/json': { $ref: '#/externalDocs/x-mocks/Order' } }
      tags:
        - order

  /orders/{orderId}:
    parameters:
      - name: orderId
        in: path
        description: order unique identifier
        required: true
        type: number
    get:
      description: Return order data with given ID
      tags:
        - order
      responses:
        200:
          description: An Object of the order
          schema:
            type: object
            items:
              $ref: '#/definitions/Order'
          examples: { 'application/json': { $ref: '#/externalDocs/x-mocks/Order' } }
    put:
      description: Update POC order data with given ID
      tags:
        - order
      parameters:
        - name: body
          in: body
          description: POC order info
          required: true
          schema:
            $ref: '#/definitions/UpdateOrder'
      responses:
        200:
          description: An Object of POC order
          schema:
            type: object
            items:
              $ref: '#/definitions/Order'
          examples: { 'application/json': { $ref: '#/externalDocs/x-mocks/Order' } }
    delete:
      description: Delete order with given ID
      tags:
        - order
      responses:
        204:
          description: success

  /orders/{orderId}/deploy:
    parameters:
      - name: orderId
        in: path
        description: order unique identifier
        required: true
        type: number
    post:
      description: deploy app to device.
      responses:
        201:
          description: deploy app to device successfully
          schema:
            type: object
            items:
              $ref: '#/definitions/DeployOrder'
          examples: { 'application/json': { $ref: '#/externalDocs/x-mocks/DeployOrder' } }
      tags:
        - order

definitions:
  Order:
    type: object
    properties:
      tenantId:
        type: string
        description: Unique identifier representing a specific tenant.
      tenantUserId:
        type: string
        description: Unique identifier representing a specific tenant user.
      orderId:
        type: number
        description: POC order ID.
      orderName:
        type: string
        description: POC order name. (default = IIoT Application Suite)
      orderNo:
        type: string
        description: POC order number.
      description:
        type: string
        description: Description of order.
      appPackDownloadUrl:
        type: string
        description: App download link for this order.
      deviceList:
        type: array
        items:
          type: object
        description: device list for this order.
      edgeAppList:
        type: array
        items:
          type: object
        description: edge app list for this order.
      deviceProfile:
        type: array
        items:
          type: object
        description: device profile.
      creator:
        type: string
        description: POC order creator.
      createdAt:
        type: string
        description: POC order created time.

  CreateOrder:
    type: object
    properties:
      deviceProfileId:
        type: number
        description: Device Profile ID.
      description:
        type: string
        description: POC order description.
      deviceId:
        type: array
        items:
          type: string
        description: device uuid list.
      appVersionId:
        type: array
        items:
          type: number
        description: edge app version id list.

  UpdateOrder:
    type: object
    properties:
      orderName:
        type: string
        description: POC order name.
      description:
        type: string
        description: POC order description.

  DeployOrder:
    type: object
    properties:
      task:
        type: string
        description: default "job operation"
      action:
        type: string
        description: default "create job–install application"
      content:
        type: object
        description: payload content

externalDocs:
  url: 'http://#'
  x-mocks:
    Order:
      {
        "orderId": 17,
        "orderName": "IIoT Application Suite",
        "orderNo": "O20181107150754",
        "tenantId": "a163dd88-d0a6-45a6-b042-e89a0bf31fbd",
        "tenantUserId": "8a849228-b3fd-41f6-bfd6-84574580e40b",
        "appPackDownloadUrl": "http://thingspro9dev4system.blob.core.windows.net/pocorder/a163dd88-d0a6-45a6-b042-e89a0bf31fbd/17.tar",
        "creator": "Zack",
        "createdAt": "2018-11-07T07:07:54.087862Z",
        "description": "test poc order",
        "deviceProfile": {
          "architecture": "armhf",
          "id": 3,
          "name": "UC-8112-LX",
          "path": "",
          "support": true
        },
        "deviceList": [
          {
            "deviceId": "2f606359-6939-490d-8114-4a2b3e104c9a",
            "deviceName": "2f606359-6939-490d-8114-4a2b3e104c9a",
            "mac": "DB-00-E7-ED-AF-3D",
            "modelName": "UC-8112-LX",
            "status": "Unknown"
          },
          {
            "deviceId": "346d9463-a60a-4d6a-b419-f59f11e07ff5",
            "deviceName": "name",
            "mac": "0C-F5-00-F3-83-92",
            "modelName": "UC-8112-LX",
            "status": "Unknown"
          }
        ],
        "edgeAppList": [
          {
            "appId": 1,
            "appName": "app-azure",
            "appVersionId": 29,
            "categoryList": [
                {
                    "categoryId": 2,
                    "categoryName": "Cloud Connectivity",
                    "description": "Cloud Connectivity"
                }
            ],
            "cpuArch": "amd64",
            "description": "MOXA Azure client",
            "displayName": "Azure Client",
            "downloadUrl": "https://thingspro9stage4system.blob.core.windows.net/edge-application/edge-app-azure/32/app-azure_0.7.0-32_amd64.mpkg",
            "iconUrl": "https://thingspro9stage4system.blob.core.windows.net/edge-application/edge-app-azure/32/images/logo.png",
            "isTrialLicense": true,
            "licenseStatement": "Trial - 30 days",
            "publishAt": "2018-11-08T01:24:15.640068Z",
            "publisher": "Moxa-ISD",
            "trialPeriodInDay": 30,
            "unitPrice": null,
            "validAt": "2018-11-08T01:24:15.640068Z",
            "version": "0.7.0-32"
          },
          {
            "appId": 2,
            "appName": "console",
            "appVersionId": 18,
            "categoryList": [
                {
                    "categoryId": 3,
                    "categoryName": "Edge Intelligence",
                    "description": "Edge Intelligence"
                }
            ],
            "cpuArch": "amd64",
            "description": "Web console",
            "displayName": "Console",
            "downloadUrl": "https://thingspro9stage4system.blob.core.windows.net/edge-application/edge-app-console/6/console_0.3.0-6_amd64.mpkg",
            "iconUrl": "https://thingspro9stage4system.blob.core.windows.net/edge-application/edge-app-console/6/images/logo.png",
            "isTrialLicense": true,
            "licenseStatement": "Trial - 30 days",
            "publishAt": "2018-10-16T06:19:39.604631Z",
            "publisher": "Moxa-ISD",
            "trialPeriodInDay": 30,
            "unitPrice": null,
            "validAt": "2018-10-16T06:19:39.604631Z",
            "version": "0.3.0-6"
          }
        ]
      }
    OrderList:
      {
        "count": 5,
        "offset": 0,
        "limit": 100,
        "data":
          [
            {
              "appPackDownloadUrl": null,
              "createdAt": "2018-08-20T05:06:58.047171Z",
              "creator": "Cain Chen",
              "description": "test poc order",
              "deviceProfile": {
                "architecture": "armhf",
                "id": 3,
                "name": "UC-8112-LX",
                "path": "",
                "support": true
              },
              "deviceList": [
                {
                  "deviceId": "346d9463-a60a-4d6a-b419-f59f11e07ff5",
                  "deviceName": "name",
                  "mac": "FE-96-32-BC-5C-BE",
                  "modelName": "UC-8112-LX",
                  "status": "Unknown"
                },
                {
                  "deviceId": "2f606359-6939-490d-8114-4a2b3e104c9a",
                  "deviceName": "2f606359-6939-490d-8114-4a2b3e104c9a",
                  "mac": "DB-00-E7-ED-AF-3D",
                  "modelName": "UC-8112-LX",
                  "status": "Unknown"
                }
              ],
              "edgeAppList": [
                {
                  "appId": 1,
                  "appName": "app-azure",
                  "appVersionId": 29,
                  "categoryList": [
                    {
                      "categoryId": 2,
                      "categoryName": "Cloud Connectivity",
                      "description": "Cloud Connectivity"
                    }
                  ],
                  "cpuArch": "amd64",
                  "description": "MOXA Azure client",
                  "displayName": "Azure Client",
                  "downloadUrl": "https://thingspro9dev4system.blob.core.windows.net/edge-application/edge-app-azure/32/app-azure_0.7.0-32_amd64.mpkg",
                  "iconUrl": "https://thingspro9dev4system.blob.core.windows.net/edge-application/edge-app-azure/32/images/logo.png",
                  "isTrialLicense": true,
                  "licenseStatement": "Trial - 30 days",
                  "publishAt": "2018-11-08T01:24:15.640068Z",
                  "publisher": "Moxa-ISD",
                  "trialPeriodInDay": 30,
                  "unitPrice": null,
                  "validAt": "2018-11-08T01:24:15.640068Z",
                  "version": "0.7.0-32"
                },
                {
                  "appId": 2,
                  "appName": "console",
                  "appVersionId": 18,
                  "categoryList": [
                    {
                      "categoryId": 3,
                      "categoryName": "Edge Intelligence",
                      "description": "Edge Intelligence"
                    }
                  ],
                  "cpuArch": "amd64",
                  "description": "Web console",
                  "displayName": "Console",
                  "downloadUrl": "https://thingspro9dev4system.blob.core.windows.net/edge-application/edge-app-console/6/console_0.3.0-6_amd64.mpkg",
                  "iconUrl": "https://thingspro9dev4system.blob.core.windows.net/edge-application/edge-app-console/6/images/logo.png",
                  "isTrialLicense": true,
                  "licenseStatement": "Trial - 30 days",
                  "publishAt": "2018-10-16T06:19:39.604631Z",
                  "publisher": "Moxa-ISD",
                  "trialPeriodInDay": 30,
                  "unitPrice": null,
                  "validAt": "2018-10-16T06:19:39.604631Z",
                  "version": "0.3.0-6"
                }
              ],
              "orderId": 120,
              "orderName": "IIoT Application Suite",
              "orderNo": "O20181113095423",
              "tenantId": "a163dd88-d0a6-45a6-b042-e89a0bf31fbd",
              "tenantUserId": "8a849228-b3fd-41f6-bfd6-84574580e40b"
            },
            {
              "appPackDownloadUrl": null,
              "createdAt": "2018-08-20T05:06:58.047171Z",
              "creator": "Cain Chen",
              "description": "test poc order",
              "deviceProfile": {
                "architecture": "armhf",
                "id": 3,
                "name": "UC-8112-LX",
                "path": "",
                "support": true
              },
              "deviceList": [
                {
                  "deviceId": "346d9463-a60a-4d6a-b419-f59f11e07ff5",
                  "deviceName": "name",
                  "mac": "FE-96-32-BC-5C-BE",
                  "modelName": "UC-8112-LX",
                  "status": "Unknown"
                },
                {
                  "deviceId": "2f606359-6939-490d-8114-4a2b3e104c9a",
                  "deviceName": "2f606359-6939-490d-8114-4a2b3e104c9a",
                  "mac": "DB-00-E7-ED-AF-3D",
                  "modelName": "UC-8112-LX",
                  "status": "Unknown"
                }
              ],
              "edgeAppList": [
                {
                  "appId": 1,
                  "appName": "app-azure",
                  "appVersionId": 29,
                  "categoryList": [
                    {
                      "categoryId": 2,
                      "categoryName": "Cloud Connectivity",
                      "description": "Cloud Connectivity"
                    }
                  ],
                  "cpuArch": "amd64",
                  "description": "MOXA Azure client",
                  "displayName": "Azure Client",
                  "downloadUrl": "https://thingspro9dev4system.blob.core.windows.net/edge-application/edge-app-azure/32/app-azure_0.7.0-32_amd64.mpkg",
                  "iconUrl": "https://thingspro9dev4system.blob.core.windows.net/edge-application/edge-app-azure/32/images/logo.png",
                  "isTrialLicense": true,
                  "licenseStatement": "Trial - 30 days",
                  "publishAt": "2018-11-08T01:24:15.640068Z",
                  "publisher": "Moxa-ISD",
                  "trialPeriodInDay": 30,
                  "unitPrice": null,
                  "validAt": "2018-11-08T01:24:15.640068Z",
                  "version": "0.7.0-32"
                },
                {
                  "appId": 2,
                  "appName": "console",
                  "appVersionId": 18,
                  "categoryList": [
                    {
                      "categoryId": 3,
                      "categoryName": "Edge Intelligence",
                      "description": "Edge Intelligence"
                    }
                  ],
                  "cpuArch": "amd64",
                  "description": "Web console",
                  "displayName": "Console",
                  "downloadUrl": "https://thingspro9dev4system.blob.core.windows.net/edge-application/edge-app-console/6/console_0.3.0-6_amd64.mpkg",
                  "iconUrl": "https://thingspro9dev4system.blob.core.windows.net/edge-application/edge-app-console/6/images/logo.png",
                  "isTrialLicense": true,
                  "licenseStatement": "Trial - 30 days",
                  "publishAt": "2018-10-16T06:19:39.604631Z",
                  "publisher": "Moxa-ISD",
                  "trialPeriodInDay": 30,
                  "unitPrice": null,
                  "validAt": "2018-10-16T06:19:39.604631Z",
                  "version": "0.3.0-6"
                }
              ],
              "orderId": 119,
              "orderName": "IIoT Application Suite",
              "orderNo": "O20181113093054",
              "tenantId": "a163dd88-d0a6-45a6-b042-e89a0bf31fbd",
              "tenantUserId": "8a849228-b3fd-41f6-bfd6-84574580e40b"
            }
          ]
      }
    DeployOrder:
      {
        "action": "create job–install application",
        "content": {
          "deviceId": [
            "346d9463-a60a-4d6a-b419-f59f11e07ff5",
            "2f606359-6939-490d-8114-4a2b3e104c9a"
          ],
          "isScheduleJob": false,
          "properties": {
            "desiredProperties": [
              {
                "id": 120,
                "name": "tobeInstall",
                "type": "application",
                "value": "http://thingspro9dev4system.blob.core.windows.net/pocorder/a163dd88d0a645a6b042e89a0bf31fbd/120.pack"
              }
            ]
          },
          "requesterId": "8a849228-b3fd-41f6-bfd6-84574580e40b",
          "scheduleAt": "",
          "tenantId": "a163dd88-d0a6-45a6-b042-e89a0bf31fbd"
        },
        "task": "job operation"
      }