swagger: '2.0'

info:
  version: 0.0.1
  title: ThingsPro Tenant Portal RESTful API reference
basePath: '/api/v1'
schemes:
  - http
  - https
produces:
  - application/json
tags:
  - name: order
    description: Handles poc order data

paths:
  /orders/{orderId}:
    parameters:
      - name: orderId
        in: path
        description: order unique identifier
        required: true
        type: string
    get:
      description: Return order data with given ID
      tags:
        - order
      responses:
        200:
          description: An Object of the order
          schema:
            type: object
            items:
              $ref: '#/definitions/Order'
          examples: { 'application/json': { $ref: '#/externalDocs/x-mocks/Order' } }

definitions:
  Order:
    type: object
    properties:
      tenantId:
        type: string
        description: Unique identifier representing a specific tenant.
      tenantUserId:
        type: string
        description: Unique identifier representing a specific tenant user.
      orderId:
        type: string
        description: POC order ID.
      orderName:
        type: string
        description: POC order name. (default = IIoT Application Suite)
      orderNo:
        type: string
        description: POC order number.
      description:
        type: string
        description: Description of order.
      appPackDownloadUrl:
        type: string
        description: App download link for this order.
      deviceList:
        type: array
        items:
          type: object
        description: device list for this order.
      edgeAppList:
        type: array
        items:
          type: object
        description: edge app list for this order.
      deviceProfile:
        type: array
        items:
          type: object
        description: device profile.
      creator:
        type: string
        description: POC order creator.
      createdAt:
        type: string
        description: POC order created time.

externalDocs:
  url: 'http://#'
  x-mocks:
    Order:
      {
        "orderId": 17,
        "orderName": "IIoT Application Suite",
        "orderNo": "O20181107150754",
        "tenantId": "a163dd88-d0a6-45a6-b042-e89a0bf31fbd",
        "tenantUserId": "8a849228-b3fd-41f6-bfd6-84574580e40b",
        "appPackDownloadUrl": "http://thingspro9dev4system.blob.core.windows.net/pocorder/a163dd88-d0a6-45a6-b042-e89a0bf31fbd/17.tar",
        "creator": "Zack",
        "createdAt": "2018-11-07T07:07:54.087862Z",
        "description": "test poc order",
        "deviceProfile": {
          "architecture": "armhf",
          "id": 3,
          "name": "UC-8112-LX",
          "path": "",
          "support": true
        },
        "deviceList": [
          {
            "deviceId": "2f606359-6939-490d-8114-4a2b3e104c9a",
            "deviceName": "2f606359-6939-490d-8114-4a2b3e104c9a",
            "mac": "DB-00-E7-ED-AF-3D",
            "modelName": "UC-8112-LX",
            "status": "Unknown"
          },
          {
            "deviceId": "346d9463-a60a-4d6a-b419-f59f11e07ff5",
            "deviceName": "name",
            "mac": "0C-F5-00-F3-83-92",
            "modelName": "UC-8112-LX",
            "status": "Unknown"
          }
        ],
        "edgeAppList": [
          {
            "appId": 1,
            "appName": "app-azure",
            "appVersionId": 29,
            "categoryList": [
                {
                    "categoryId": 2,
                    "categoryName": "Cloud Connectivity",
                    "description": "Cloud Connectivity"
                }
            ],
            "cpuArch": "amd64",
            "description": "MOXA Azure client",
            "displayName": "Azure Client",
            "downloadUrl": "https://thingspro9stage4system.blob.core.windows.net/edge-application/edge-app-azure/32/app-azure_0.7.0-32_amd64.mpkg",
            "iconUrl": "https://thingspro9stage4system.blob.core.windows.net/edge-application/edge-app-azure/32/images/logo.png",
            "isTrialLicense": true,
            "licenseStatement": "Trial - 30 days",
            "publishAt": "2018-11-08T01:24:15.640068Z",
            "publisher": "Moxa-ISD",
            "trialPeriodInDay": 30,
            "unitPrice": null,
            "validAt": "2018-11-08T01:24:15.640068Z",
            "version": "0.7.0-32"
          },
          {
            "appId": 2,
            "appName": "console",
            "appVersionId": 18,
            "categoryList": [
                {
                    "categoryId": 3,
                    "categoryName": "Edge Intelligence",
                    "description": "Edge Intelligence"
                }
            ],
            "cpuArch": "amd64",
            "description": "Web console",
            "displayName": "Console",
            "downloadUrl": "https://thingspro9stage4system.blob.core.windows.net/edge-application/edge-app-console/6/console_0.3.0-6_amd64.mpkg",
            "iconUrl": "https://thingspro9stage4system.blob.core.windows.net/edge-application/edge-app-console/6/images/logo.png",
            "isTrialLicense": true,
            "licenseStatement": "Trial - 30 days",
            "publishAt": "2018-10-16T06:19:39.604631Z",
            "publisher": "Moxa-ISD",
            "trialPeriodInDay": 30,
            "unitPrice": null,
            "validAt": "2018-10-16T06:19:39.604631Z",
            "version": "0.3.0-6"
          }
        ]
      }