swagger: '2.0'

info:
  version: 0.0.1
  title: ThingsPro Admin Portal RESTful API reference
basePath: '/api/v1'
schemes:
  - http
  - https
produces:
  - application/json
securityDefinitions:
  mx-api-token:
    type: apiKey
    name: mx-api-token
    in: header
    description: ThingsPro RESTful API token, The token should be created on web console.

tags:
  - name: tenant
    description: Handles tenants data

paths:
  '/tenants':
    get:
      description: Get all tenants field data
      responses:
        200:
          description: An array of tenants
          schema:
            type: array
            items:
              $ref: '#/definitions/Tenant'
          examples: { 'application/json': { $ref: '#/externalDocs/x-mocks/TenantList' } }
      tags:
        - tenant
      security:
        - mx-api-token: []
    post:
      description: Create a new tenant.
      parameters:
        - name: body
          in: body
          description: ''
          required: true
          schema:
            $ref: '#/definitions/TenantReq'
      responses:
        201:
          description: Create tenant successfully
          schema:
            type: object
            items:
              $ref: '#/definitions/Tenant'
          examples: { 'application/json': { $ref: '#/externalDocs/x-mocks/Tenant' } }
      tags:
        - tenant
      security:
        - mx-api-token: []
  /tenants/{id}:
    parameters:
      - name: id
        in: path
        description: tenant unique identifier
        required: true
        type: string
    get:
      description: Return tenant data with given ID
      tags:
        - tenant
      security:
        - mx-api-token: []
      responses:
        200:
          description: An Object of the tenant
          schema:
            type: object
            items:
              $ref: '#/definitions/Tenant'
          examples: { 'application/json': { $ref: '#/externalDocs/x-mocks/Tenant' } }
    put:
      description: Return updated tenant data with given ID
      tags:
        - tenant
      parameters:
        - name: body
          in: body
          description: Information of tenant
          required: true
          schema:
            $ref: '#/definitions/TenantReq'
      responses:
        200:
          description: An Object of the tenant
          schema:
            type: object
            items:
              $ref: '#/definitions/Tenant'
          examples: { 'application/json': { $ref: '#/externalDocs/x-mocks/Tenant' } }
    delete:
      description: Delete tenant with given ID
      tags:
        - tenant
      security:
        - mx-api-token: []
      responses:
        204:
          description: success
  /tenants/{id}/approve:
    parameters:
      - name: id
        in: path
        description: tenant unique identifier
        required: true
        type: string
    put:
      description: Update tenant activate status
      parameters:
        - name: body
          in: body
          description: Activate status
          required: true
          schema:
            properties:
              activate:
                type: boolean
                example: true
      responses:
        200:
          description: Sucess

  /hostnames/{hostname}/available:
    parameters:
      - name: hostname
        in: path
        description: Check hostname is available or not
        required: true
        type: string
    get:
      description: Return hostname is available or not
      tags:
        - tenant
      security:
        - mx-api-token: []
      responses:
        200:
          description: success

definitions:
  Tenant:
    type: object
    properties:
      tenantId:
        type: string
        description: Unique identifier representing a specific tenant.
      domainName:
        type: string
        description: domainName of tenant.
      company:
        type: string
        description: Company of tenant.
      email:
        type: string
        description: Email of tenant.
      username:
        type: string
        description: Username of tenant admin user.
      firstName:
        type: string
        description: First name of tenant admin user.
      lastName:
        type: string
        description: Last name of tenant admin user.
      activate:
        type: boolean
        description: Activate status of tenant.
      phone:
        type: string
        description: Phone of tenant.
      culture:
        type: string
        description: Culture of tenant.
      industry:
        type: string
        description: Industry of tenant.
      customer:
        type: boolean
        description: Is customer or not.                
      provisionStatus:
        type: string
        description: Provision status of tenant.
      deviceHlr:
        type: string
        description: Device home location url.     
      data:
        type: object
        description: metadata of tenant.   
      activatedAt:
        type: string
        description: Tenant activate time, ISO data format, like '2018-08-12T20:17:46.384Z'.   
      deactivatedAt:
        type: string
        description: Tenant deactivate time,ISO data format, like '2018-08-12T20:17:46.384Z'.   
      createdAt:
        type: string
        description: Tenant created time,ISO data format, like '2018-08-12T20:17:46.384Z'.   
      updatedAt:
        type: string
        description: Tenant updated time, ISO data format, like '2018-08-12T20:17:46.384Z'.         

  TenantReq:
    type: object
    properties:
      domainName:
        type: string
        description: domainName of tenant.
        maxLength: 50
      company:
        type: string
        description: Company of tenant admin user.
        maxLength: 50
      email:
        type: string
        description: Email of tenant admin user.
        maxLength: 254
      username:
        type: string
        description: Username of tenant admin user.
        maxLength: 50
      firstName:
        type: string
        description: First name of tenant admin user.
        maxLength: 50
      lastName:
        type: string
        description: Last name of tenant admin user.
        maxLength: 50
      phone:
        type: string
        description: Phone of tenant admin user.
        maxLength: 30
      culture:
        type: string
        description: Culture of tenant.
        maxLength: 10
      industry:
        type: number
        description: Industry of tenant.
      customer:
        type: boolean
        description: Is customer or not.                  
      data:
        type: object
        description: metadata of tenant.   
           
externalDocs:
  url: 'http://#'
  x-mocks:
    Tenant:
      {
        "tenantId": "65af94c4-07e4-43d7-abad-3cb5f295550b",
        "email": "moxa@moxa.com",
        "domainName": "moxa",
        "username": "username",
        "firstName": "firstName",
        "lastName": "lastName",
        "activate": true,
        "company": "moxa",
        "phone": "1234567890",                      
        "culture": "Taiwan",
        "industry": "Telecom",
        "customer": true,
        "provisionStatus": "ok",
        "deviceHlr": "https://preview.thingspro.io",
        "activatedAt": "2018-08-12T20:17:46.384Z",
        "deactivatedAt": "2018-08-12T20:17:46.384Z",
        "createdAt": "2018-08-12T20:17:46.384Z",
        "updatedAt": "2018-08-12T20:17:46.384Z",
        "data": 
          {
            "CUSTOM_FIELD": "CUSTOM_VALUE"
          }
      }
    TenantList:
      [
        {
          "tenantId": "65af94c4-07e4-43d7-abad-3cb5f295550b",
          "email": "moxa@moxa.com",
          "domainName": "moxa",
          "username": "username",
          "firstName": "firstName",
          "lastName": "lastName",
          "activate": true,
          "company": "moxa",
          "phone": "1234567890",                      
          "culture": "Taiwan",
          "industry": "Telecom",
          "customer": true,
          "provisionStatus": "ok",
          "deviceHlr": "https://preview.thingspro.io",
          "activatedAt": "2018-08-12T20:17:46.384Z",
          "deactivatedAt": "2018-08-12T20:17:46.384Z",
          "createdAt": "2018-08-12T20:17:46.384Z",
          "updatedAt": "2018-08-12T20:17:46.384Z",
          "data": 
            {
              "CUSTOM_FIELD": "CUSTOM_VALUE"
            }
        },
        {
          "tenantId": "65af94c4-07e4-43d7-abad-3cb5f295550b",
          "email": "moxa@moxa.com",
          "domainName": "moxa",
          "username": "username",
          "firstName": "firstName",
          "lastName": "lastName",
          "activate": true,
          "company": "moxa",
          "phone": "1234567890",                      
          "culture": "Taiwan",
          "industry": "Telecom",
          "customer": true,
          "provisionStatus": "ok",
          "deviceHlr": "https://preview.thingspro.io",
          "activatedAt": "2018-08-12T20:17:46.384Z",
          "deactivatedAt": "2018-08-12T20:17:46.384Z",
          "createdAt": "2018-08-12T20:17:46.384Z",
          "updatedAt": "2018-08-12T20:17:46.384Z",
          "data": 
            {
              "CUSTOM_FIELD": "CUSTOM VALUE"
            }
        }
      ]
    TenantReq: 
      {
        "email": "moxa@moxa.com",
        "domainName": "moxa",
        "username": "username",
        "firstName": "firstName",
        "lastName": "lastName",
        "company": "moxa",
        "phone": "1234567890",                      
        "culture": "Taiwan",
        "industry": 1,
        "customer": true,
        "data": 
          {
            "CUSTOM_FIELD": "CUSTOM_VALUE"
          }
      } 
    