swagger: '2.0'

info:
  version: 0.0.0
  title: DLM Company Portal RESTful API reference
basePath: '/api/v1'
schemes:
  - http
  - https
produces:
  - application/json
tags:
  - name: offer
    description: Handles offer apply function

paths:
  /offers:
    get:
      description: Get all offer data
      parameters:
        - name: sort
          in: query
          description: Sorting the filter group list, default is desc
          required: false
          type: string
          enum:
          - desc
          - asc
        - name: limit
          in: query
          description: max return groups count (default is 100 and max is 1000)
          required: false
          type: integer
        - name: offset
          in: query
          description: offset
          required: false
          type: integer
      responses:
        200:
          description: An array of apply offer 
          schema:
            type: array
            items:
              $ref: '#/definitions/Offer'
            example: 
              $ref: '#/externalDocs/x-mocks/OfferList'
      tags:
        - offer
    post:
      description: Create a new offer.
      parameters:
        - name: body
          in: body
          description: ''
          required: true
          schema:
            type: object
            items:
              $ref: '#/definitions/OfferCreate'
            example:
              $ref: '#/externalDocs/x-mocks/OfferCreate'    
      responses:
        201:
          description: Create offer successfully
          schema:
            type: object
            items:
              $ref: '#/definitions/Offer'
            example:
              $ref: '#/externalDocs/x-mocks/Offer'
      tags:
        - offer

  /offer/{offer_id}:
    parameters:
      - name: offer_id
        in: path
        description: offer unique identifier
        required: true
        type: integer
    get:
      description: Return offer data with given ID
      tags:
        - offer
      responses:
        200:
          description: An Object of the offer
          schema:
            type: object
            items:
              $ref: '#/definitions/Offer'
            example:
              $ref: '#/externalDocs/x-mocks/Offer'

definitions:
  Offer:
    type: object
    properties:
      offerId:
        type: integer
        description: Unique identifier representing a specific offer.
      offerName:
        type: string
        description: Name of Offer.
      product:
        type: string
        enum:
        - Standard
        - Professional
        description: Product type of offer.
      description:
        type: string
        description: Description of Offer.
      duration:
        type: integer
        description: Commit month of offer, should be [0-12], 0 presents infinte.  
      price:
        type: number
        format: float
        description: Price of offer
      deviceLimit:
        type: integer
        description: Limit number of devices
      deviceOverage:
        type: boolean
        description: Device can overage or not.
      deviceOverageRate:
        type: number
        format: float
        description: Price of overage device.
      apiLimit:
        type: integer
        description: Limit number of api  
      apiOverage:
        type: boolean
        description: Api can overage or not.
      apiOverageRate:
        type: number
        format: float
        description: Price of overage api.
      status:
        type: boolean
        description: enable or disable.
      createdAt:
        type: string
        description: Offer created time, ISO data format, like '2018-08-12T20:17:46.384Z'.
   
  OfferCreate:
    type: object
    required:
      - offerName
      - product
      - duration
      - price
      - deviceLimit
      - deviceOverage
      - deviceOverageRate
      - apiLimit
      - apiOverage
      - apiOverageRate
    properties:
      offerName:
        type: string
        description: Name of Offer.
      product:
        type: string
        enum:
        - Standard
        - Professional
        description: Product type of offer.
      description:
        type: string
        description: Description of Offer.
      duration:
        type: integer
        description: Commit month of offer, should be [1-12], -1 presents infinte.  
      price:
        type: number
        format: float
        description: Price of offer
      deviceLimit:
        type: integer
        description: Limit number of devices, -1 presents infinte.
      deviceOverage:
        type: boolean
        description: Device can overage or not.
      deviceOverageRate:
        type: number
        format: float
        description: Price of overage device.
      apiLimit:
        type: integer
        description: Limit number of api, -1 presents infinte.
      apiOverage:
        type: boolean
        description: Api can overage or not.
      apiOverageRate:
        type: number
        format: float
        description: Price of overage api.

externalDocs:
  url: 'http://#'
  x-mocks:
    Offer:
      {
        "offerId": 1,
        "offerName": "SDE",
        "description": "SDE",
        "price": 0,
        "product": "basic",
        "duration": -1,
        "deviceLimit": -1,
        "deviceOverage": true,
        "deviceOverageRate": 0,
        "apiLimit": -1,
        "apiOverage": true,
        "apiOverageRate": 0,
        "status": true,
        "createdAt": "2019-03-26T07:51:35.663935Z"
      }
    OfferList:
      {
        "count": 5,
        "offset": 0,
        "limit": 100,
        "data":
          [
            {
              "offerId": 1,
              "offerName": "SDE",
              "description": "SDE",
              "price": 0,
              "product": "basic",
              "duration": -1,
              "deviceLimit": -1,
              "deviceOverage": true,
              "deviceOverageRate": 0,
              "apiLimit": -1,
              "apiOverage": true,
              "apiOverageRate": 0,
              "status": true,
              "createdAt": "2019-03-26T07:51:35.663935Z"
            }
          ]
      }
    OfferCreate:
      {
        "offerName": "SDE",
        "description": "SDE",
        "price": 0,
        "product": "basic",
        "duration": -1,
        "deviceLimit": -1,
        "deviceOverage": true,
        "deviceOverageRate": 0,
        "apiLimit": -1,
        "apiOverage": true,
        "apiOverageRate": 0
      }

