swagger: '2.0'

info:
  version: 0.0.0
  title: DLM Admin Portal RESTful API reference
basePath: '/api/v1'
schemes:
  - http
  - https
produces:
  - application/json
tags:
  - name: company
    description: Handles companys data

paths:
  /companys:
    get:
      description: Get all companys
      tags:
        - company
      parameters:
        - name: companyName
          in: query
          description: Filter the company list by company name
          required: false
          type: string
        - name: status
          in: query
          description: Filter the company list by company status
          required: false
          type: string  
          enum:
          - waiting
          - approved
          - declined
          - removed
        - name: order
          in: query
          description: The company list order by some keyword. default is order by 'createdAt'
          required: false
          type: string
          enum:
          - companyName
          - status
        - name: sort
          in: query
          description: Sorting the filter company list, default is asc
          required: false
          type: string
          enum:
          - desc
          - asc
        - name: limit
          in: query
          description: max return companys count (default is 100 and max is 1000)
          required: false
          type: integer
        - name: offset
          in: query
          description: offset
          required: false
          type: integer
      responses:
        200:
          description: An array of companys
          schema:
            type: array
            items:
              $ref: '#/definitions/Company'
            example:
              $ref: '#/externalDocs/x-mocks/CompanyList'
    post:
      description: Create a new company.
      tags:
        - company
      parameters:
        - name: body
          in: body
          description: ''
          required: true
          schema:
            $ref: '#/definitions/CompanyCreate'
      responses:
        201:
          description: Create company successfully
          schema:
            type: object
            items:
              $ref: '#/definitions/Company'
            example:
              $ref: '#/externalDocs/x-mocks/Company'

  /companys/{companyId}:
    parameters:
      - name: companyId
        in: path
        description: company unique identifier
        required: true
        type: string
    get:
      description: Return company data with given ID
      tags:
        - company
      responses:
        200:
          description: An Object of the company
          schema:
            type: object
            items:
              $ref: '#/definitions/Company'
            example:
              $ref: '#/externalDocs/x-mocks/Company'
    put:
      description: Return updated company data with given ID
      tags:
        - company
      parameters:
        - name: body
          in: body
          description: Information of company
          required: true
          schema:
            $ref: '#/definitions/CompanyUpdate'
      responses:
        200:
          description: An Object of the company
          schema:
            type: object
            items:
              $ref: '#/definitions/Company'
            example: 
              $ref: '#/externalDocs/x-mocks/Company'

  /companys/{companyId}/users:
    parameters:
      - name: companyId
        in: path
        description: company unique identifier
        required: true
        type: string
    get:
      description: Return users of company data with given ID
      tags:
        - company
      responses:
        200:
          description: An array of company users
          schema:
            type: array
            items:
              $ref: '#/definitions/User'
            example:
              $ref: '#/externalDocs/x-mocks/CompanyUserList'

definitions:
  Company:
    type: object
    properties:
      companyId:
        type: string
        description: Unique identifier representing a specific company.
      companyName:
        type: string
        description: Company name of company.
      status:
        type: string
        enum:
          - waiting
          - approved
          - declined
          - removed
        description: Status of company.
      createdAt:
        type: string
        description: company created time,ISO data format, like '2018-08-12T20:17:46.384Z'.
      updatedAt:
        type: string
        description: company updated time,ISO data format, like '2018-08-12T20:17:46.384Z'.  
  CompanyCreate:
    type: object
    properties:
      companyName:
        type: string
        description: Company name of company.
  CompanyUpdate:
    type: object
    properties:
      companyName:
        type: string
        description: Company name of company.
      status:
        type: string
        enum:
          - approved
          - declined
          - removed
        description: Status of company.

externalDocs:
  url: 'http://#'
  x-mocks:
    Company:
      {
        "companyId": "ed31872d-b57e-4c94-a989-c2782c0d3fe7",
        "companyName": "MOXA",
        "status": "approved",
        "createdAt": "2019-03-08T07:18:27:565Z",
        "updatedAt": "2019-03-08T07:18:27:565Z"
      }
    CompanyList:
      {
        "count": 13,
        "data": [
          {
            "companyId": "ed31872d-b57e-4c94-a989-c2782c0d3fe7",
            "companyName": "MOXA",
            "status": "approved",
            "createdAt": "2019-03-08T07:18:27:565Z",
            "updatedAt": "2019-03-08T07:18:27:565Z"
          }
        ],
        "limit": 1,
        "offset": 0
      }
    CompanyCreate:
      {
        "companyName": "MOXA"
      }
    CompanyUpdate:
      {
        "companyName": "MOXA",
        "status": "approved"
      }
    CompanyUserList:
      {
        "count": 28,
        "data": [
          {
            "companyId": "07473967-3c29-4914-b275-d0511c42554e",
            "userId": "a1be69eb-258e-4c66-b07b-583474e57305",
            "status": "enable",
            "role": {
                "roleId": 2,
                "name": "Administrator",
                "admin": true,
                "permissions": [
                  {
                    "id": 1,
                    "value": 0
                  },
                  {
                    "id": 2,
                    "value": 0
                  }
                ]
            },
            "username": "owen",
            "email": "owen@moxa.com",
            "createdAt": "2019-03-08T08:44:13.425Z",
            "updatedAt": "2019-03-08T08:44:13.425Z",
            "loginedAt": "",  
            "passwordExpiredAt": "2019-01-22T07:51:26.214Z"
          }
        ],
        "limit": 1,
        "offset": 1
      }

    