swagger: '2.0'

info:
  version: 0.0.1
  title: ThingsPro Tenant Portal RESTful API reference
basePath: '/api/v1'
schemes:
  - http
  - https
produces:
  - application/json
tags:
  - name: group
    description: Handles tenant groups data

paths:
  /groups:
    get:
      description: Get all groups field data
      parameters:
        - name: deviceId
          in: query
          type: string
          description: 'Get group device belongs to'
      responses:
        200:
          description: An array of group
          schema:
            type: array
            items:
              $ref: '#/definitions/GroupListObj'
          examples: { 'application/json': { $ref: '#/externalDocs/x-mocks/GroupList' } }
      tags:
        - group
    post:
      description: Create a new group.
      parameters:
        - name: body
          in: body
          description: ''
          required: true
          schema:
            $ref: '#/definitions/GroupReq'
      responses:
        201:
          description: Create group successfully
          schema:
            type: object
            items:
              $ref: '#/definitions/Group'
          examples: { 'application/json': { $ref: '#/externalDocs/x-mocks/Group' } }
      tags:
        - group
 
  /groups/{groupId}:
    parameters:
      - name: groupId
        in: path
        description: group unique identifier
        required: true
        type: string
    get:
      description: Return group data with given ID
      tags:
        - group
      responses:
        200:
          description: An Object of the group
          schema:
            type: object
            items:
              $ref: '#/definitions/Group'
          examples: { 'application/json': { $ref: '#/externalDocs/x-mocks/Group' } }
    delete:
      description: Delete group with given ID
      tags:
        - group
      responses:
        204:
          description: success
    patch:
      description: Update group settings
      parameters:
      - name: body
        in: body
        required: true
        schema:
          type: array
          items:
            $ref: '#/definitions/GroupUpdate'
      responses:
        200:
          description: success
          schema:
            $ref: '#/definitions/Group'
          examples:
            {
              "application/json": {
                $ref: '#/externalDocs/x-mocks/Group'
              }
            } 
  /groups/{groupId}/unassignDevices:
    parameters:
      - name: groupId
        in: path
        description: group unique identifier
        required: true
        type: string
    get:
      description: Return all devies don't belong to this group
      parameters:
        - name: distinct
          in: query
          description: Get distict value of speific field, this query parameter will return string array only
          required: false
          type: string
          enum:
          - deviceName
          - modelName
        - name: order
          in: query
          description: Ordering the filter device list, default is desc
          required: false
          type: string
          enum:
          - desc
          - asc
        - name: sort
          in: query
          description: Sort the device list by specific ordering, default is sort by 'lastUpdatedAt'
          required: false
          type: string
          enum:
          - deviceName
          - modelName
        - name: limit
          in: query
          description: max return devices count (default is 100 and max is 1000)
          required: false
          type: integer
        - name: offset
          in: query
          description: offset
          required: false
          type: integer
      tags:
        - group
      responses:
        200:
          description: An Object of the group
          schema:
            type: object
            items:
              $ref: '#/definitions/DevicePoc'
          examples: { 'application/json': { $ref: '#/externalDocs/x-mocks/DevicePocList' } }

  /groups/{groupId}/desiredProperties:
    parameters:
      - name: groupId
        in: path
        description: group unique identifier
        required: true
        type: string
    get:
      description: Return common desired properties data with given ID group
      tags:
        - group
      responses:
        200:
          description: An Object of the desired properties
          schema:
            type: object
            items:
              $ref: '#/definitions/DesiredProperties'
          examples: { 'application/json': { $ref: '#/externalDocs/x-mocks/DesiredProperties' } }

  /groups/{groupId}/directMethodList:
    parameters:
      - name: groupId
        in: path
        description: group unique identifier
        required: true
        type: string
    get:
      description: Return direct methods data with given ID group
      tags:
        - group
      responses:
        200:
          description: An Object of the direct methods
          schema:
            type: object
            items:
              $ref: '#/definitions/DirectMethodList'
          examples: { 'application/json': { $ref: '#/externalDocs/x-mocks/DirectMethodList' } }

definitions:
  Group:
    type: object
    properties:
      groupId:
        type: integer
        description: Unique identifier representing a specific tenant group.
      tenantId:
        type: string
        description: Unique identifier representing a specific tenant.
      groupName:
        type: string
        description: Name of group.
      description:
        type: string
        description: Description of group.  
      devices:
        type: array
        items:
          $ref: '#/definitions/DevicePoc'
        description: Devices belong to this group     
      updatedAt:
        type: string
        description: Group updated time, ISO data format, like '2018-08-12T20:17:46.384Z'.         

  GroupListObj:
    type: object
    properties:
      groupId:
        type: integer
        description: Unique identifier representing a specific tenant group.
      tenantId:
        type: string
        description: Unique identifier representing a specific tenant.
      groupName:
        type: string
        description: Name of group.
      description:
        type: string
        description: Description of group.  
      deviceIdList:
        type: array
        items:
          type: string
        description: id of devices belong to this group   
      updatedAt:
        type: string
        description: Group updated time, ISO data format, like '2018-08-12T20:17:46.384Z'.   

  GroupReq:
    type: object
    required:
      - groupName
      - description
      - devicdIdList
    properties:
      groupName:
        type: string
        description: Group name.
      description:
        type: string
        description: Group descripton.
      devicdIdList:
        type: array
        items:
          type: string
        description: Device UUID list.    

  GroupUpdate:
    type: object
    properties:
      groupName:
        type: string
        description: Group name.
      description:
        type: string
        description: Group descripton.
      devicdIdList:
        type: array
        items:
          type: string
        description: Device UUID list. 

  DesiredProperties:
    type: object
    properties:
      desiredLastUpdatedAt:
        type: string
        description: Device desired properties updated time, ISO data format, like '2018-08-12T20:17:46.384Z'.   
      desiredProperties:
        type: array
        items:
          type: object
        description: Device desired properties.
        
  DirectMethodList:
    type: object
    properties:
      directMethodList:
        type: array
        items:
          type: object
        description: Device direct method list.
  
  DevicePoc:
    type: object
    properties:
      deviceId:
        type: string
        description: Unique identifier representing a specific device.
      deviceName:
        type: string
        description: Device name.
      modelName:
        type: string
        description: Model name of device.
      mac:
        type: string
        description: MAC address of device.

externalDocs:
  url: 'http://#'
  x-mocks:
    Group:
      {
        "tenantId": "65af94c4-07e4-43d7-abad-3cb5f295550b",
        "groupId": "4b4f1ab2-18ac-483e-aedd-2aaeb2dabd59",
        "groupName": "moxa",
        "devicdIdList": ["1", "2"],
        "devices": [
          {
            "deviceId": "a960aa2b-67ab-4bd3-a85e-a006aeb7fa0b",
            "deviceName": "UC-8112-LX",
            "mac": "81-CF-1C-14-3E-4C",
            "modelName": "UC-8112-LX"
          },
          {
            "deviceId": "91cc56a9-1159-4913-b5f2-ac482cd68ee6",
            "deviceName": "UC-8112-LX",
            "mac": "67-88-DE-3C-F1-54",
            "modelName": "UC-8112-LX"
          }
        ],
        "description": "moxa group",
        "updatedAt": "2018-08-12T20:17:46.384Z"
      }
    GroupList:
      [
        {
          "tenantId": "65af94c4-07e4-43d7-abad-3cb5f295550b",
          "groupId": 1,
          "groupName": "moxa",
          "devicdIdList": ["1", "2"],
          "description": "moxa group",
          "createdAt": "2018-08-12T20:17:46.384Z",
          "updatedAt": "2018-08-12T20:17:46.384Z"
        },
        {
          "tenantId": "65af94c4-07e4-43d7-abad-3cb5f295550b",
          "groupId": 2,
          "groupName": "moxa2",
          "devicdIdList": ["1", "3"],
          "description": "moxa group2",
          "createdAt": "2018-08-12T20:17:46.384Z",
          "updatedAt": "2018-08-12T20:17:46.384Z"
        }
      ]
    GroupReq:
      {
        "groupName": "moxa3",
        "description": "moxa group3",
        "devicdIdList": ["1", "2"]
      }
    DesiredProperties:
      { 
        "desiredLastUpdatedAt": "2018-08-12T20:17:46.384Z",
        "desiredProperties": [        
          {
            "id": 1,
            "type": "general",
            "name": "deviceName",
            "description": "Device Name",
            "value": "Demo Device 01"
          },
          {
            "id": 2,
            "type": "general",
            "name": "firmwareVersion",
            "description": "Firmware Version",
            "value": "1.8.1"
          },      
          {
            "id": 3,
            "type": "general",
            "name": "configVersion",
            "description": "Config Version",
            "value": "3.1.2"
          },
          {
            "id": 4,
            "type": "network",
            "name": "eth0",
            "description": "Ethernet 0",
            "value": [
              {
                "id": 1,
                "name": "ipAddress",
                "description": "IP Address",
                "value": "192.168.3.21"
              },
              {
                "id": 2,
                "name": "mask",
                "description": "Subnet Mask",
                "value": "255.255.255.0"
              },
              {
                "id": 3,
                "name": "gateway",
                "description": "Default Gateway",
                "value": "192.168.3.254"
              },
              {
                "id": 4,
                "name": "dhcp",
                "description": "DHCP",
                "value": true
              },
              {
                "id": 5,
                "name": "primaryDns",
                "description": "Primary DNS",
                "value": "192.168.3.254"
              },
              {
                "id": 6,
                "name": "secondaryDns",
                "description": "Secondary DNS",
                "vaule": "10.29.11.121"
              }
            ]
          }          
        ]
      }
    DirectMethodList:
      {    
        "directMethodList": [
          {
            "methodName": "reboot",
            "displayName": "Reboot",
            "description": "Reboot IoT Device immediately",
            "userInput": []
          },
          {
            "methodName": "rebootAt",
            "displayName": "Reboot At",
            "description": "Reboot IoT Device at a specific date time",
            "userInput": [
              {
                "parameter": "executeAt",
                "value": "",
                "dataType": "datetime",
                "description": "UTC time with ISO 8601 format"
              }
            ]
          }
        ]      
      }
    DevicePocList:
      {
        "count": 3,
        "offset": 0,
        "limit": 100,
        "data": [
          {
            "deviceId": "a960aa2b-67ab-4bd3-a85e-a006aeb7fa0b",
            "deviceName": "UC-8112-LX",
            "mac": "81-CF-1C-14-3E-4C",
            "modelName": "UC-8112-LX"
          },
          {
            "deviceId": "91cc56a9-1159-4913-b5f2-ac482cd68ee6",
            "deviceName": "UC-8112-LX",
            "mac": "67-88-DE-3C-F1-54",
            "modelName": "UC-8112-LX"
          },
          {
            "deviceId": "47c03400-3e45-466d-abd4-4e01199cd67a",
            "deviceName": "UC-8112-LX",
            "mac": "DF-FE-F1-9E-FF-76",
            "modelName": "UC-8112-LX"
          }
        ]
      }