swagger: '2.0'

info:
  version: 0.0.1
  title: ThingsPro Tenant Portal RESTful API reference
basePath: '/api/v1'
schemes:
  - http
  - https
produces:
  - application/json
tags:
  - name: profile
    description: Handles tenants data

paths:
  /profiles:
    get:
      description: Get all device profile field data
      responses:
        200:
          description: An array of device profile
          schema:
            type: array
            items:
              $ref: '#/definitions/Profile'
          examples: { 'application/json': { $ref: '#/externalDocs/x-mocks/ProfileList' } }
      tags:
        - profile

  /profiles/{profileId}:
    parameters:
      - name: profileId
        in: path
        description: profile unique identifier
        required: true
        type: string
    get:
      description: Return device profile data with given ID
      tags:
        - profile
      responses:
        200:
          description: An Object of the device profile
          schema:
            type: object
            items:
              $ref: '#/definitions/Profile'
          examples: { 'application/json': { $ref: '#/externalDocs/x-mocks/Profile' } }

  /profiles/getDeviceModelList:
    get:
      description: Return all device model data
      tags:
        - profile
      responses:
        200:
          description: An Object of the device model
          schema:
            type: object
            items:
              $ref: '#/definitions/DeviceModel'
          examples: { 'application/json': { $ref: '#/externalDocs/x-mocks/DeviceModel' } }

definitions:
  Profile:
    type: object
    properties:
      id:
        type: integer
        description: Unique identifier representing a specific device profile.
      name:
        type: string
        description: Name of device profile.
      profile:
        type: object
        properties:
          allowExtendModule:
            type: boolean
            description: Allow app to be installed
          generalInfo:
            type: object
            properties:
              architecture:
                type: string
                description: CPU architecture
              cpu:
                type: string
                description: CPU detail information
              deviceType:
                type: string
                description: unknown. (always 'IIoT Gateway')
              edgeVersion:
                type: string
                description: thingspro edge version
              firmwareVersion:
                type: string
                description: thingspro firmware version
              modelName:
                type: string
                description: device profile modle name
          directMethodList:
            type: array
            description: Direct method list.
            items:
              type: object

  DeviceModel:
    type: object
    properties:
      directMethodList:
        type: array
        items:
          type: object
          properties:
            id:
              type: integer
              description: device model id
            name:
              type: string
              description: device model name
            architecture:
              type: string
              description: CPU architecture
            support:
              type: boolean
              description: whether to allow app to be installed
            path:
              type: string
              description: app icon path
        description: All device model list.

externalDocs:
  url: 'http://#'
  x-mocks:
    Profile:
      {
        "id": 3,
        "name": "UC-8112-LX",
        "profile": {
          "allowExtendModule": true,
          "directMethodList": [
            {
              "description": "Reboot IoT Device at a specific date time",
              "displayName": "Reboot At",
              "methodName": "rebootAt",
              "systemInput": [
                {
                  "dataType": "string",
                  "description": "A reference ID between Server and Edge",
                  "parameter": "rebootId",
                  "value": "$taskId"
                }
              ],
              "userInput": [
                {
                  "dataType": "datetime",
                  "description": "UTC time with ISO 8601 format",
                  "parameter": "executeAt",
                  "value": ""
                }
              ]
            }
          ],
          "generalInfo": {
              "architecture": "armhf",
              "cpu": "ARM32 1Ghz",
              "deviceType": "IIoT Gateway",
              "edgeVersion": "3.1.2",
              "firmwareVersion": "1.8.1",
              "modelName": "UC-8112-LX"
          },
          "moduleList": [
            "docker",
            "message-broker",
            "sanji-framework",
            "thingspro-apps"
          ]
        }
      }
    ProfileList:
      [
        {
          "id": 3,
          "name": "UC-8112-LX",
          "profile": {
            "allowExtendModule": true,
            "generalInfo": {
                "architecture": "armhf",
                "cpu": "ARM32 1Ghz",
                "deviceType": "IIoT Gateway",
                "edgeVersion": "3.1.2",
                "firmwareVersion": "1.8.1",
                "modelName": "UC-8112-LX"
            }
          }
        },
        {
          "id": 4,
          "name": "MC-1100",
          "profile": {
            "allowExtendModule": true,
            "generalInfo": {
                "architecture": "armhf",
                "cpu": "ARM32 1Ghz",
                "deviceType": "IIoT Gateway",
                "edgeVersion": "3.1.2",
                "firmwareVersion": "1.8.1",
                "modelName": "MC-1100"
            }
          }
        }
      ]
    DeviceModelList:
      [
        {
          "architecture": "armhf",
          "id": 3,
          "name": "UC-8112-LX",
          "path": "http://thingspro9dev4system.blob.core.windows.net/images/device/moxa/UC-8112-LX/90x90.jpg",
          "support": true
        },
        {
          "architecture": "armhf",
          "id": 4,
          "name": "MC-1100",
          "path": "http://thingspro9dev4system.blob.core.windows.net/images/device/moxa/MC-1100/90x90.jpg",
          "support": true
        },
        {
          "architecture": "armhf",
          "id": 1,
          "name": "MB-3660",
          "path": "http://thingspro9dev4system.blob.core.windows.net/images/device/moxa/MB-3660/90x90.jpg",
          "support": false
        }
      ]
    DeviceModel:
      {
        "architecture": "armhf",
        "id": 1,
        "name": "MB-3660",
        "path": "http://thingspro9dev4system.blob.core.windows.net/images/device/moxa/MB-3660/90x90.jpg",
        "support": false
      }
