swagger: '2.0'

info:
  version: 0.0.1
  title: ThingsPro Gateway RESTful API reference
basePath: '/api/v1'
schemes:
  - http
  - https
produces:
  - application/json
securityDefinitions:
  mx-api-token:
    type: apiKey
    name: mx-api-token
    in: header
    description: ThingsPro RESTful API token, The token should be created on web console.

tags:
  - name: login
    description: Handles login/logout operation

paths:
  '/login':
    post:
      description: user login
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              username:
                type: string
                example: 'moxa'
              password:
                type: string
                example: '12345678'
      responses:
        200:
          description: Return user and token data
          schema:
            $ref: '#/definitions/LoginRes'
          example: 
            $ref: '#/externalDocs/x-mocks/LoginRes'
      tags:
        - login
      security:
        - mx-api-token: []
  '/logout':
    post:
      description: user logout
      responses:
        200:
          description: user logout
      tags:
        - logout
      security:
        - mx-api-token: []

definitions:
  LoginRes:
    type: object
    properties:
      user:
        type: object
        items:
          - $ref: '#/definitions/User'
      token:
        type: string
        description: Granted authentication token.

externalDocs:
  url: '#'
  x-mocks:
    LoginRes:
      {
        user:
          {
            "id": 1,
            "name": "Moxa",
            "company": "moxa",
            "email": "moxa@moxa.com",
            "adminRole": 0,
            "data": 
              {
                "CUSTOM_FIELD": "CUSTOM_VALUE"
              }
          },
        token: "USER_TOKEN"
      }
