swagger: '2.0'

info:
  version: 0.0.0
  title: DLM Company Portal RESTful API reference
basePath: '/api/v1'
schemes:
  - http
  - https
produces:
  - application/json
tags:
  - name: project
    description: Handles projects data

paths:
  /enroll:
    post:
      description: Return enroll certificate and key
      tags:
        - project
      parameters:
        - name: body
          in: body
          description: Information of device
          required: true
          schema:
            $ref: '#/definitions/EnrollReq'
      responses:
        200:
          description: Response enroll certificate and key
          schema:
            type: object
            items:
              $ref: '#/definitions/EnrollRes'
            example: 
              $ref: '#/externalDocs/x-mocks/EnrollRes'

  /register:
    post:
      description: Return register certificate and key
      tags:
        - project
      parameters:
        - name: body
          in: body
          description: Information of device
          required: true
          schema:
            $ref: '#/definitions/RegisterReq'
      responses:
        200:
          description: Response register certificate and key and connection information
          schema:
            type: object
            items:
              $ref: '#/definitions/RegisterRes'
            example: 
              $ref: '#/externalDocs/x-mocks/RegisterRes'

  
definitions:
  EnrollReq:
    type: object
    required:
    - mac
    - serialNumber
    - modelName
    - projectId
    properties:
      mac:
        type: string
        description: Device mac.
      serialNumber:
        type: string
        description: Device serial number.  
      modelName:
        type: string
        description: Device model name. 
      projectId:
        type: string
        description: project unique identifier
  EnrollRes:
    type: object
    description: Return enroll PK and cert, the default mode is hyperlink mode, server will response(enrollPKLink + enrollCertLink), if mode=text in query string, server will response (enrollPK + enrollCert)
    properties:
      deviceId:
        type: string
        description: Device id.
      enrollPK:
        type: string
        description: Private key.
      enrollCert:
        type: string
        description: Certificate.
      projectId:
        type: string
        description: project unique identifier
      projectName:
        type: string
        description: project name
  RegisterReq:
    type: object
    required:
    - mac
    - serialNumber
    - modelName
    properties:
      mac:
        type: string
        description: Device mac.
      serialNumber:
        type: string
        description: Device serial number.  
      modelName:
        type: string
        description: Device model name. 
  RegisterRes:
    type: object
    description: Return enroll PK and cert, the default mode is hyperlink mode, server will response(enrollPKLink + enrollCertLink), if mode=text in query string, server will response (enrollPK + enrollCert)
    properties:
      deviceId:
        type: string
        description: Device id.
      registerCA:
        type: object
        description: Register cert and private key.
      data:
        type: object
        description: information for connect to cloud
      newEnrollCA:
        type: object
        description: Enroll cert and private key, Only send when old cert will expire nearby, .
      
externalDocs:
  url: 'http://#'
  x-mocks:
    EnrollReq:
      {
        "mac": "001122334455",
        "serialNumber": "12345678",
        "modelName": "UC-8112A-ME-T-LX",
        "projectId": "65af94c4-07e4-43d7-abad-3cb5f295550b"
      }
    EnrollRes:
      {
        "deviceId": "65af94c4-07e4-43d7-abad-3cb5f295550b",
        "projectId": "65af94c4-07e4-43d7-abad-3cb5f295550b",
        "projectName": "test",
        "enrollPK": "moxa",
        "enrollCert": "moxa"
      }
    RegisterReq:
      {
        "mac": "001122334455",
        "serialNumber": "12345678",
        "modelName": "UC-8112A-ME-T-LX"
      }
    RegisterRes:
      {
        "error": {
          "code": 100,
          "reason": "Register failure reason"
        },
        "data": 
          {
            "scenario": "aws_iot_core",
            "hostname": "http://www.moxa.com",
            "authType": "x509"
          },
        "registerCA": 
          {
            "registerPK": "moxa",
            "registerCert": "moxa"
          },
        "newEnrollCA": 
          {
            "enrollPK": "moxa",
            "enrollCert": "moxa"
          }
      }  

    