---
swagger: '2.0'

info:
  title: Modbus Tag Read/Write Access API
  description: Modbus Tag Access for Data acquisition
  version: '0.0.1'
schemes:
- http
- https
produces:
- application/json
securityDefinitions:
  mx-api-token:
    type: apiKey
    name: mx-api-token
    in: header
    description: ThingsPro RESTful API token, The token should be created on web console.

tags:
- name: access
  description: Modbus Tag Access for Data Acquisition

paths:
  /mxc/modbus/access/{equipment}/{tag}:
    parameters:
    - name: equipment
      description: equipment name of tags
      in: path
      type: string
      required: true
    - name: tag
      description: tag name of tags
      in: path
      type: string
      required: true

    get:
      description: Read Modbus Tag of (Equipent,Tag)
      responses:
        200:
          description: success
          schema:
            $ref: '#/definitions/ModbusReadRsp'
          example:
            {
              "application/json": {
                $ref: '#/externalDocs/x-mocks/ModbusReadEquTagRspExample'
              }
            }
      tags:
      - access
      security:
      - mx-api-token: []

    put:
      description: Write Modbus Tag of (Equipment,Tag)
      parameters:
      - name: body
        in: body
        required: true
        schema:
          type: array
          items:
            $ref: '#/definitions/ModbusWriteEquTagReq'
      responses:
        200:
          description: success
          schema:
            $ref: '#/definitions/ModbusWriteRsp'
          example:
            {
              "application/json": {
                $ref: '#/externalDocs/x-mocks/ModbusWriteEquTagRspExample'
              }
            }
      tags:
      - access
      security:
      - mx-api-token: []

definitions:
  ModbusWriteEquTagReq:
    title: Modbus Write Request Entry of (Equipment,Tag)
    description: Modbus Write Request of (Equipment,Tag)
    type: object
    required:
    - valueType
    - value
    properties:
      valueType:
        type: string
      value:
        type: object

  ModbusReadRsp:
    title: Modbus Read Response Entry
    description: Modbus Read Response
    type: object
    required:
    - equipmentName
    - tagName
    - valueType
    - value
    properties:
      equipmentName:
        type: string
      tagName:
        type: string
      valueType:
        type: string
      value:
        type: object

  ModbusWriteRsp:
    title: Modbus Write Response Entry
    description: Modbus Write Response
    type: object
    required:
    - equipmentName
    - tagName
    properties:
      equipmentName:
        type: string
      tagName:
        type: string

externalDocs:
  url: '#'
  x-mocks:
    ModbusReadEquTagRspExample:
      {
        "equipmentName": "ioLogik-E1210",
        "tagName": "di0",
        "valueType": "bool",
        "value": true
      }

    ModbusWriteEquTagRspExample:
      {
        "equipmentName": "ioLogik-E1210",
        "tagName": "di0"
      }
