---
swagger: '2.0'

info:
  title: Modbus Management API
  description: Modbus Management for Data acquisition
  version: '0.0.1'

schemes:
- http
- https

produces:
- application/json

tags:
- $ref: './equipment-template.yaml#/tags'
- $ref: './interface.yaml#/tags'
- $ref: './access.yaml#/tags'

paths:
- $ref: './equipment-template.yaml#/paths'
- $ref: './interface.yaml#/paths'
- $ref: './access.yaml#/paths'

definitions:
- $ref: './equipment-template.yaml#/definitions'
- $ref: './interface.yaml#/definitions'
- $ref: './access.yaml#/definitions'
