swagger: '2.0'

info:
  version: 2.1.0
  title: ThingsPro Gateway RESTful API reference
basePath: '/api/v1'
schemes:
  - http
  - https
produces:
  - application/json
securityDefinitions:
  mx-api-token:
    type: apiKey
    name: mx-api-token
    in: header
    description: ThingsPro RESTful API token, The token should be created on web console.

tags:
  - name: status
    description: Provides system status information

paths:
  '/system/status':
    get:
      parameters:
        - name: fields
          in: query
          required: false
          type: string
          description: Only get selected fields. Using comma as separator (?fields=cpuUsage,uptimeSec,version)
      description: Get system status
      responses:
        '200':
          description: success
          schema:
            '$ref': '#/definitions/SystemStatus'
            example:
              hostname: Moxa
              version: 1.1.0-1
              uptimeSec: 312956
              cpuUsage: 5.7
              memoryUsage: 63.8
              memory: 257286144
              disks:
                - name: system
                  mount: '/'
                  device: rootfs
                  usage:
                    total: 770695168
                    used: 497655808
                    free: 217038848
                    percent: 64.6
                - name: sd1
                  mount: '/media/sd-mmcblk1p1'
                  device: '/dev/mmcblk1p1'
                  usage:
                    total: 770695168
                    used: 497655808
                    free: 217038848
                    percent: 64.6
      tags:
        - status
      security:
        - mx-api-token: []
    put:
      parameters:
        - name: body
          in: body
          required: true
          schema:
            '$ref': '#/definitions/SystemStatus'
      description: Update hostname
      responses:
        '200':
          description: success
          schema:
            '$ref': '#/definitions/SystemStatus'
            example:
              hostname: Moxa
              version: 1.1.0-1
              uptimeSec: 312956
              cpuUsage: 5.7
              memoryUsage: 63.8
              memory: 257286144
              disks:
                - name: system
                  mount: '/'
                  device: rootfs
                  usage:
                    total: 770695168
                    used: 497655808
                    free: 217038848
                    percent: 64.6
                - name: sd1
                  mount: '/media/sd-mmcblk1p1'
                  device: '/dev/mmcblk1p1'
                  usage:
                    total: 770695168
                    used: 497655808
                    free: 217038848
                    percent: 64.6
      tags:
        - status
      security:
        - mx-api-token: []
  '/system/reboot':
    post:
      description: 'Reboot system (delay: 3 sec)'
      responses:
        '200':
          description: success
      tags:
        - status
      security:
        - mx-api-token: []
  '/system/syslog':
    post:
      parameters:
        - name: body
          in: body
          required: true
          schema:
            '$ref': '#/definitions/UrlInfo'
      description: Uplaod system logs to remote server
      responses:
        '200':
          description: sucess
          schema:
            '$ref': '#/definitions/UrlInfo'
            example:
              url: https://www.google.com
      tags:
        - status
      security:
        - mx-api-token: []
  '/network/interfaces':
    get:
      description: Get network interfaces
      responses:
        '200':
          description: success
          schema:
            '$ref': '#/definitions/NetworkInterfaces'
            example:
              - tunl0
              - eth0
              - eth1
      tags:
        - status
      security:
        - mx-api-token: []
  '/system/password':
    put:
      parameters:
        - name: body
          in: body
          required: true
          schema:
            '$ref': '#/definitions/SystemPassword'
      description: Update OS password
      responses:
        '200':
          description: success
      tags:
        - status
      security:
        - mx-api-token: []
  '/system/properties':
    get:
      description: Get system properties
      responses:
        '200':
          description: success
          schema:
            '$ref': '#/definitions/SystemProperties'
            example:
              gps:
                lat: 121.123
                lng: 22.456
              aliasName: my iot gateway
      tags:
        - status
      security:
        - mx-api-token: []
  '/system/properties/{key}':
    parameters:
      - name: key
        in: path
        type: string
        required: true
    get:
      description: Get specific system property
      responses:
        '200':
          description: success
          schema:
            allOf:
              - '$ref': '#/definitions/SystemProperties/properties/aliasName'
              - '$ref': '#/definitions/SystemProperties/properties/gps'
          examples:
            application/json:
              lat: 121.123
              lng: 22.456
      tags:
        - status
      security:
        - mx-api-token: []
    put:
      description: Update specific system property
      parameters:
        - name: body
          in: body
          required: true
          schema:
            '$ref': '#/definitions/SystemPropertiesUpdate'
      responses:
        '200':
          description: success
          schema:
            example:
              lat: 121.123
              lng: 22.456
      tags:
        - status
      security:
        - mx-api-token: []
  '/mxc/system/equipments':
    get:
      description: Get system tag information
      responses:
        '200':
          description: success
          schema:
            '$ref': '#/definitions/Equipments'
            example:
              - equipmentName: SYSTEM
                equipmentTags:
                  - name: cpu_usage
                    dataType: float64
                    access: ro
                    size: 8
                    description: CPU Usage
                  - name: memory_usage
                    dataType: float64
                    access: ro
                    size: 8
                    description: Memory Usage
                  - name: disk_usage
                    dataType: float64
                    access: ro
                    size: 8
                    description: Disk Usage
      tags:
        - status
      security:
        - mx-api-token: []

definitions:
  SystemStatus:
    description: System status
    type: object
    properties:
      hostname:
        description: Hostname
        type: string
        minLength: 1
        maxLength: 63
        pattern: '/^(?![0-9]+$)(?!.*-$)(?!-)[a-zA-Z0-9-]{1,63}$/'
      version:
        description: Version of system
        type: string
        readOnly: true
      uptimeSec:
        description: 'System uptime (unit: seconds)'
        type: string
        readOnly: true
      cpuUsage:
        description: CPU usage (in percentage)
        type: number
        readOnly: true
      memoryUsage:
        description: System memory usage (in percentage)
        type: number
        readOnly: true
      memory:
        description: 'System total memory (unit: byte)'
        type: integer
        readOnly: true
      disks:
        type: array
        readOnly: true
        items:
          '$ref': '#/definitions/Disk'
    example:
      hostname: Moxa
      version: 1.1.0-1
      uptimeSec: 312956
      cpuUsage: 5.7
      memoryUsage: 63.8
      memory: 257286144
      disks:
        - name: system
          mount: '/'
          device: rootfs
          usage:
            total: 770695168
            used: 497655808
            free: 217038848
            percent: 64.6
        - name: sd1
          mount: '/media/sd-mmcblk1p1'
          device: '/dev/mmcblk1p1'
          usage:
            total: 770695168
            used: 497655808
            free: 217038848
            percent: 64.6
  Disk:
    description: Disk information
    type: object
    readOnly: true
    properties:
      name:
        description: Disk alias
        type: string
        readOnly: true
      mount:
        description: Mount point
        type: string
        readOnly: true
      device:
        description: Physical device node path
        type: string
        readOnly: true
      usage:
        description: Usage of this disk
        type: object
        readOnly: true
        properties:
          total:
            description: 'Total size (unit: byte)'
            type: integer
            readOnly: true
          used:
            description: 'Used size (unit: byte)'
            type: integer
            readOnly: true
          free:
            description: 'Free size (unit: byte)'
            type: integer
            readOnly: true
          percent:
            description: Percent of used size
            type: number
            readOnly: true
  NetworkInterfaces:
    description: Network Interfaces
    type: array
    items:
      type: string
    example:
      url: https://server/upload
      headers:
        accessToken: MOXAMOXA-TEST-SYSTEM
  SystemPassword:
    description: System Password
    required:
      - password
    type: object
    properties:
      password:
        description: password
        type: string
        minLength: 4
        maxLength: 255
    example:
      passowrd: thisisyourpassword
  SystemProperties:
    description: System Properties
    type: object
    properties:
      aliasName:
        description: Alias name of this device
        type: string
        maxLength: 255
        default: MOXA IoT Gateway
      gps:
        description: GPS location information
        type: object
        required:
          - lat
          - lng
        properties:
          lat:
            type: number
            format: float
            description: latitude
            default: 0
          lng:
            type: number
            format: float
            description: longitude
            default: 0
    example:
      gps:
        lat: 121.123
        lng: 22.456
      aliasName: my iot gateway
  SystemPropertiesUpdate:
    description: Request payload for updating system property
    type: object
    required:
      - data
    properties:
      data:
        type: object
        allOf:
          - '$ref': '#/definitions/SystemProperties/properties/aliasName'
          - '$ref': '#/definitions/SystemProperties/properties/gps'
    example:
      data:
        lat: 121.123
        lng: 22.456
  Equipments:
    description: system tags
    type: array
    items:
      type: object
      required:
        - equipmentName
        - equipmentTags
      properties:
        equipmentName:
          description: equipment name of tags
          type: string
          minLength: 3
          maxLength: 255
        equipmentTags:
          description: list of tags
          type: array
          items:
            type: object
            required:
              - name
              - dataType
              - access
              - size
              - description
            properties:
              name:
                description: Name of tag
                type: string
                minLength: 1
                maxLength: 255
              dataType:
                description: Data type of tag
                type: string
                enum:
                  - boolean
                  - uint16
                  - uint32
                  - uint64
                  - int16
                  - int32
                  - int64
                  - float32
                  - float64
                  - string
                  - bytearray
              access:
                description: Access type of tag
                type: string
                enum:
                  - ro
                  - wo
                  - rw
              size:
                description: Size of tag in byte
                type: integer
              description:
                description: Description of tag
                type: string
                minLength: 0
                maxLength: 4096
