---
swagger: '2.0'

tags:
- $ref: "./device.yaml#/tags"
- $ref: "./modelProfile.yaml#/tags"

paths:
- $ref: "./device.yaml#/tags"
- $ref: "./modelProfile.yaml#/tags"

definitions:
- $ref: "./device.yaml#/definitions"
- $ref: "./modelProfile.yaml#/definitions"
