swagger: '2.0'

info:
  version: 0.0.2
  title: DLM Partner Portal RESTful API reference
  description: |
    Welcome to the DLM Partner Portal RESTful API reference.

host: localhost
basePath: '/api/v1'

schemes:
  - http
  - https

produces:
  - application/json

tags:
  - $ref: './device/index.yaml#/tags'

paths:
  - $ref: './device/index.yaml#/paths'

definitions:
  - $ref: './device/index.yaml#/definitions'
