swagger: '2.0'

info:
  version: 0.0.0
  title: ThingsPro Gateway RESTful API reference
basePath: '/api/v1'
schemes:
  - http
  - https
produces:
  - application/json
securityDefinitions:
  mx-api-token:
    type: apiKey
    name: mx-api-token
    in: header
    description: ThingsPro RESTful API token, The token should be created on web console.

tags:
  - name: deviceJobRelay
    description: Non-Blocking IO Model

paths:
  /deviceJobRelay:
    post:
      tags:
        - deviceJobRelay
      security:
        - mx-api-token: []
      description: New API<br />Create a device task by non-blocking io model
      consumes:
        - application/json
      parameters:
        - name: body
          in: body
          description: Parameters of device task
          required: true
          schema:
            $ref: '#/definitions/DeviceJobRelayCreate'
      responses:
        '201':
          description: Response of device task
          schema:
            $ref: '#/definitions/DeviceJobRelayResponse'
            example:
              $ref: '#/externalDocs/x-mocks/DeviceJobRelayResponse'
  
  /deviceJobRelay/{id}:
    parameters:
      - name: id
        in: path
        description: Device task unique identifier
        required: true
        type: string
    get:
      security:
        - mx-api-token: []
      tags:
        - deviceJobRelay
      description: New API<br />Return Device task data with given id
      responses:
        '200':
          description: An Object of the device task
          schema:
            type: object
            items:
              $ref: '#/definitions/DeviceJobRelay'
            example:
              $ref: '#/externalDocs/x-mocks/DeviceJobRelay'

definitions:
  DeviceJobRelayCreate:
    type: object
    required:
      - deviceUUID
      - payload
    properties:
      deviceUUID:
        description: Target device's uuid
        type: string
      payload:
        type: object
        description: >-
          RESTful Message, for more detail please refer to ThingsPro Gateway
          RESTful Reference
        required:
          - method
          - resource
        properties:
          method:
            description: method of this request message
            type: string
            enum:
              - get
              - post
              - put
              - delete
          resource:
            type: string
            description: resource of this request message
          data:
            description: Body
            allOf:
              - type: array
                description: array data
                items:
                  - type: string
              - type: object
                description: object data
    example:
      $ref: '#/externalDocs/x-mocks/DeviceJobRelayCreate'
  DeviceJobRelayResponse:
    type: object
    required:
      - deviceUUID
    properties:
      deviceUUID:
        description: Target device's uuid
        type: string
      taskId:
        description: Task ID
        type: string
    example:
      $ref: '#/externalDocs/x-mocks/DeviceJobRelayResponse'
  DeviceJobRelay:
    type: object
    required:
      - taskId
    properties:
      taskId:
        description: Task ID
        type: string
      status:
        description: response status
        type: string
      updatedAt:
        description: updated time
        type: string
      code:
        description: http status code
        type: number
      payload:
        description: payload of result
        type: object
    example:
      $ref: '#/externalDocs/x-mocks/DeviceJobRelay'

externalDocs:
  url: 'http://#'
  x-mocks:
    DeviceJobRelayCreate:
      deviceUUID: 2730e69e-8d5a-4642-a7cf-966365f991fd
      payload:
        method: get
        resource: /system/serial
    DeviceJobRelayResponse:
      deviceUUID: 2730e69e-8d5a-4642-a7cf-966365f991fd
      taskId: job_1a9947d8-f97b-43a0-a1c6-eac5a65c2c01_1551157796.874439
    DeviceJobRelay:
      taskId: job_1a9947d8-f97b-43a0-a1c6-eac5a65c2c01_1551157796.874439
      status: Success from CG
      updatedAt: 2018-10-02T10:02:36Z
      code: 200
      payload: 
        deviceUUID: 19c487dc-27c1-405b-bfce-000000000001
        method: get
        resource: /system/serial
        data:
          - id: 1
            devDisplayName: PORT 1
            dev: /dev/ttyM0
            mode: rs232
