swagger: '2.0'

info:
  version: 0.0.0
  title: ThingsPro Tenant Portal RESTful API reference
basePath: '/api/v1'
schemes:
  - http
  - https
produces:
  - application/json

tags:
  - name: tenant
    description: Handles user field data

paths:
  /tenant/info:
    get:
      description: get tenant info
      responses:
        200:
          description: Return tenant info
          schema:
            $ref: '#/definitions/TenantInfo'
          example: 
            $ref: '#/externalDocs/x-mocks/TenantInfo'
      tags:
        - tenant

  /tenant/avatar:
    put:
      description: Upload an image file for tenant
      tags:
        - tenant
      consumes:
        - multipart/form-data
      parameters:
        - name: image
          in: formData
          description: use form-data to upload a image. key = image, value = {image file}
          required: true
          type: file
      responses:
        200:
          description: Upload an image file
          schema:
            type: object
            items:
              $ref: '#/definitions/Avatar'
            example:
              $ref: '#/externalDocs/x-mocks/Avatar'

definitions:
  Avatar:
    type: object
    properties:
      exist:
        type: string
        description: Return download path of avatar

  Offer:
    type: object
    properties:
      price:
        type: integer
        description: Price of this offer

  Subscription:
    type: object
    properties:
      name:
        type: string
        description: Name of subscribe service.
      status:
        type: string
        description: Status of subscribe service.
        enum:
        - activated
        - deactivated
      startTime:
        type: string
        description: Start time of subscribe service.
      endTime:
        type: string
        description: End time of subscribe service.
      offer:
        type: object
        description: Offer of subscribe service.
        items:
          '$ref': '#/definitions/Offer'
      autoRenew:
        type: boolean
        description: Subscrption automatically renews at the end of your subscrption's expiry period.

  TenantInfo:
    type: object
    properties:
      tenantId:
        type: string
        description: Unique identifier representing a specific tenant.
      domainName:
        type: string
        description: Domain name of tenant.
      portalName:
        type: string
        description: Portal name of tenant.
      email:
        type: string
        description: Email of tenant.
      activate:
        type: string
        description: Activate status of tenant.
      culture:
        type: string
        description: Culture of tenant.
      industry:
        type: string
        description: Industry of tenant.
      avatar:
        type: string
        description: Avatar of user.
      customer:
        type: boolean
        description: Is customer or not.
      provisionStatus:
        type: string
        description: Provision status of tenant.
      supporter:
        type: string
        description: Tenant supporter name.
      supporterEmail:
        type: string
        description: Tenant supporter email.
      data:
        type: object
        description: metadata of tenant.
      activatedAt:
        type: string
        description: Tenant activate time, ISO data format, like '2018-08-12T20:17:46.384Z'.
      deactivatedAt:
        type: string
        description: Tenant deactivate time,ISO data format, like '2018-08-12T20:17:46.384Z'.
      createdBy:
        type: string
        description: Created tenant username
      createdAt:
        type: string
        description: Tenant created time,ISO data format, like '2018-08-12T20:17:46.384Z'.
      updatedAt:
        type: string
        description: Tenant updated time, ISO data format, like '2018-08-12T20:17:46.384Z'.
      subscriptions:
        type: array
        description: Subscribe services of the tenant.
        items:
          '$ref': '#/definitions/Subscription'

externalDocs:
  url: 'http://#'
  x-mocks:
    Avatar:
      { 
        "path": "https://www.moxa.com/images/avatar/user/7dc93587-5444-48bf-a196-da811c39959d.jpg" 
      }
    TenantInfo:
      {
        "activate": "approved",
        "activatedAt": "",
        "avatar": "https://www.moxa.com/images/avatar/tenant/ed31872d-b57e-4c94-a989-c2782c0d3fe7.jpeg",
        "createdAt": "2019-01-22T07:49:07.104674Z",
        "createdBy": "Rick Peng",
        "culture": "zh-TW",
        "customer": false,
        "data": {},
        "deactivatedAt": "",
        "domainName": "tenant-dev",
        "industry": "Others",
        "portalName": "ISS",
        "supporter": "Rick Peng",
        "supporterEmail": "rick.peng@moxa.com",
        "provisionStatus": "Provision Completed. Email Sent Completed.",
        "supporter": "Rick Peng",
        "supporterEmail": "rick.peng@moxa.com",
        "tenantId": "ed31872d-b57e-4c94-a989-c2782c0d3fe7",
        "subscription": 
        [
          {
            "name": "Device Management",
            "status": "activated",
            "startTime": 2019-03-20T07:49:07.104674Z", 
            "endTime": 2019-04-20T07:49:07.104674Z",
            "offer": {
              "price": 20
            },
            "autoRenew": True
          }
        ],
        "updatedAt": "2019-01-22T07:49:07.104674Z"
      }