swagger: '2.0'

info:
  version: 0.0.1
  title: DLM Admin Portal RESTful API reference
  description: |
    Welcome to the DLM Admin Portal RESTful API reference.
host: localhost
basePath: '/api/v1'

schemes:
  - http
  - https

produces:
  - application/json

securityDefinitions:
  mx-api-token:
    type: apiKey
    name: bearer
    in: header
    description: DLM RESTful API token, The token will create when user login.

tags:
  - $ref: './offer/index.yaml#/tags'
  - $ref: './tenant/index.yaml#/tags'
  - $ref: './user/index.yaml#/tags'

paths:
  - $ref: './offer/index.yaml#/paths'
  - $ref: './tenant/index.yaml#/paths'
  - $ref: './user/index.yaml#/paths'

definitions:
  - $ref: './offer/index.yaml#/definitions'
  - $ref: './tenant/index.yaml#/definitions'
  - $ref: './user/index.yaml#/definitions'
