swagger: '2.0'

info:
  version: 2.1.0
  title: ThingsPro Gateway RESTful API reference
basePath: '/api/v1'
schemes:
  - http
  - https
produces:
  - application/json
securityDefinitions:
  mx-api-token:
    type: apiKey
    name: mx-api-token
    in: header
    description: ThingsPro RESTful API token, The token should be created on web console.

tags:
  - name: iptables
    description: Manages iptables rules

paths:
  '/network/portmapping':
    get:
      summary: Port Mapping Rule(s)
      description: List all port mapping rules.
      responses:
        '200':
          description: An array of port mapping rule(s)
          schema:
            type: array
            items:
              '$ref': '#/definitions/PortMapping'
            example:
              - id: 1
                enable: true
                service: http
                extPort:
                  start: 8080
                  end: 8080
                intPort:
                  start: 80
                  end: 80
                intIp: 192.168.5.123
                protocol: tcp
              - id: 2
                enable: false
                service: test
                extPort:
                  start: 10080
                  end: 10083
                intPort:
                  start: 8080
                  end: 8083
                intIp: 192.168.5.123
                protocol: both
      tags:
        - iptables
      security:
        - mx-api-token: []
    post:
      parameters:
        - name: body
          in: body
          required: true
          schema:
            '$ref': '#/definitions/PortMapping'
      summary: Create a Port Mapping Rule
      description: Append a port mapping rule in the table.
      responses:
        '200':
          description: OK
          schema:
            '$ref': '#/definitions/PortMapping'
            example:
              id: 1
              enable: true
              service: http
              extPort:
                start: 8080
                end: 8080
              intPort:
                start: 80
                end: 80
              intIp: 192.168.5.123
              protocol: tcp
      tags:
        - iptables
      security:
        - mx-api-token: []
    delete:
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: array
            items:
              description: Target rule ID
              type: integer
      description: Delete multiple rules
      responses:
        '200':
          description: success
      tags:
        - iptables
      security:
        - mx-api-token: []
  '/network/portmapping/{id}':
    get:
      description: Get a port mapping rule by ID
      responses:
        '200':
          description: success
          schema:
            '$ref': '#/definitions/PortMapping'
            example:
              id: 1
              enable: true
              service: http
              extPort:
                start: 8080
                end: 8080
              intPort:
                start: 80
                end: 80
              intIp: 192.168.5.123
              protocol: tcp
      tags:
        - iptables
      security:
        - mx-api-token: []
    parameters:
      - name: id
        in: path
        type: integer
        required: true
    put:
      parameters:
        - name: body
          in: body
          required: true
          schema:
            '$ref': '#/definitions/PortMapping'
      summary: Update a Port Mapping Rule
      description: Update a port mapping rule in the table.
      responses:
        '200':
          description: OK
          schema:
            '$ref': '#/definitions/PortMapping'
            example:
              id: 1
              enable: true
              service: http
              extPort:
                start: 8080
                end: 8080
              intPort:
                start: 80
                end: 80
              intIp: 192.168.5.123
              protocol: tcp
      tags:
        - iptables
      security:
        - mx-api-token: []
    delete:
      description: Delete port mapping rule by ID
      responses:
        '200':
          description: success
      tags:
        - iptables
      security:
        - mx-api-token: []
  '/network/ssnat':
    get:
      summary: Simple SNAT Rule(s)
      description: List all simple source NAT rules.
      responses:
        '200':
          description: An array of simple SNAT rule(s)
          schema:
            type: array
            items:
              '$ref': '#/definitions/SSNAT'
            example:
              - id: 1
                enable: true
                priority: 0
                service: http
                protocol: both
                intIp: 192.168.5.123
                portStart: 80
                portEnd: 80
                outInterface: wan
              - id: 2
                enable: false
                priority: 1
                service: https
                protocol: both
                intIp: 192.168.5.123
                portStart: 443
                portEnd: 443
                outInterface: wan
      tags:
        - iptables
      security:
        - mx-api-token: []
    post:
      parameters:
        - name: body
          in: body
          required: true
          schema:
            '$ref': '#/definitions/SSNAT'
      summary: Create a Simple SNAT Rule
      description: |
        Create a simple source NAT rule in the table, only internal IP,
        source port, and internal IP is provided.
      responses:
        '200':
          description: OK
          schema:
            '$ref': '#/definitions/SSNAT'
            example:
              id: 1
              enable: true
              priority: 0
              service: http
              protocol: both
              intIp: 192.168.5.123
              portStart: 80
              portEnd: 80
              outInterface: wan
      tags:
        - iptables
      security:
        - mx-api-token: []
    delete:
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: array
            items:
              description: Target rule ID
              type: integer
      description: Delete multiple rules
      responses:
        '200':
          description: success
      tags:
        - iptables
      security:
        - mx-api-token: []
  '/network/ssnat/{id}':
    get:
      description: Get a simple source NAT rule by ID
      responses:
        '200':
          description: success
          schema:
            '$ref': '#/definitions/SSNAT'
            example:
              id: 1
              enable: true
              priority: 0
              service: http
              protocol: both
              intIp: 192.168.5.123
              portStart: 80
              portEnd: 80
              outInterface: wan
      tags:
        - iptables
      security:
        - mx-api-token: []
    parameters:
      - name: id
        in: path
        type: integer
        required: true
    put:
      parameters:
        - name: body
          in: body
          required: true
          schema:
            '$ref': '#/definitions/SSNAT'
      summary: Update a Simple SNAT Rule
      description: Update a simple source NAT rule in the table.
      responses:
        '200':
          description: OK
          schema:
            '$ref': '#/definitions/SSNAT'
            example:
              id: 1
              enable: true
              priority: 0
              service: http
              protocol: both
              intIp: 192.168.5.123
              portStart: 80
              portEnd: 80
              outInterface: wan
      tags:
        - iptables
      security:
        - mx-api-token: []
    delete:
      description: Delete simple source NAT rule by ID
      responses:
        '200':
          description: success
      tags:
        - iptables
      security:
        - mx-api-token: []
  '/network/firewall/wan/https':
    get:
      description: Get the firewall status for HTTPS on WAN
      responses:
        '200':
          description: status
          schema:
            '$ref': '#/definitions/FirewallWanHttps'
            example:
              enable: false
      tags:
        - iptables
      security:
        - mx-api-token: []
    put:
      parameters:
        - name: body
          in: body
          required: true
          schema:
            '$ref': '#/definitions/FirewallWanHttps'
      description: Update the firewall status for HTTPS on WAN
      responses:
        '200':
          description: OK
          schema:
            '$ref': '#/definitions/FirewallWanHttps'
            example:
              enable: false
      tags:
        - iptables
      security:
        - mx-api-token: []

definitions:
  PortMapping:
    title: PortMapping
    required:
      - enable
      - extPort
      - intPort
      - intIp
      - protocol
    properties:
      id:
        type: integer
        description: Identifier for a Port Mapping rule.
      enable:
        type: boolean
        description: Indicate to enable (true) or disable (false) the rule.
      service:
        type: string
        description: The service name for Port Mapping.
        pattern: '[A-Za-z0-9_-]+'
        minLength: 0
        maxLength: 255
      extPort:
        type: object
        description: External port(s) of the rule.
        required:
          - start
        properties:
          start:
            description: Start port of the rule.
            type: integer
            minimum: 1
            maximum: 65535
          end:
            description: End port of the rule.
            type: integer
            minimum: 1
            maximum: 65535
      intPort:
        type: object
        description: Internal port(s) of the rule.
        required:
          - start
        properties:
          start:
            description: Start port of the rule.
            type: integer
            minimum: 1
            maximum: 65535
          end:
            description: End port of the rule.
            type: integer
            minimum: 1
            maximum: 65535
      intIp:
        type: string
        pattern: "^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$"
        description: Destination IP address for the rule.
      protocol:
        type: string
        enum:
          - tcp
          - udp
          - both
        description: Specify the protocol for the rule.
    example:
      id: 1
      enable: true
      service: http
      extPort:
        start: 8080
        end: 8080
      intPort:
        start: 80
        end: 80
      intIp: 192.168.5.123
      protocol: tcp
  SSNAT:
    title: SSNAT
    required:
      - enable
      - portStart
      - intIp
      - protocol
    properties:
      id:
        type: integer
        description: Identifier for a simple SNAT rule.
      enable:
        type: boolean
        description: Indicate to enable (true) or disable (false) the rule.
      service:
        type: string
        description: The service name for simple SNAT. Default to `0`.
        pattern: '[A-Za-z0-9_-]+'
        minLength: 0
        maxLength: 255
      priority:
        type: integer
        description: Rule priority, larger number has the higher priority.
        minimum: 0
        maximum: 999
      portStart:
        type: integer
        minimum: 1
        maximum: 65535
        description: Start port of the rule.
      portEnd:
        type: integer
        minimum: 1
        maximum: 65535
        description: End port of the rule.
      intIp:
        type: string
        pattern: "^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$"
        description: Internal (source) IP address for the source NAT.
      protocol:
        type: string
        enum:
          - tcp
          - udp
          - both
        description: Specify the protocol for the rule.
      outInterface:
        type: string
        pattern: '[A-Za-z0-9]'
        minLength: 2
        maxLength: 255
        description: 'Could be the interface name or "wan" to indicate a WAN interface.'
    example:
      id: 1
      enable: true
      priority: 0
      service: http
      protocol: both
      intIp: 192.168.5.123
      portStart: 80
      portEnd: 80
      outInterface: wan
  FirewallWanHttps:
    title: FirewallWanHttps
    required:
      - enable
    properties:
      enable:
        type: boolean
        description: Indicate to enable (true) or disable (false) the rule.
    example:
      enable: false
