swagger: '2.0'

info:
  version: 0.0.0
  title: ThingsPro Tenant Portal RESTful API reference
basePath: '/api/v1'
schemes:
  - http
  - https
produces:
  - application/json

tags:
  - name: login

paths:
  /login:
    post:
      description: user login
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              username:
                type: string
                example: 'thingspro@moxa.com'
              password:
                type: string
                example: '12345678'
      responses:
        200:
          description: Return user and token data
          schema:
            $ref: '#/definitions/LoginRes'
            example: 
              $ref: '#/externalDocs/x-mocks/LoginRes'
      tags:
        - user

  /logout:
    post:
      description: user logout
      responses:
        200:
          description: user logout
      tags:
        - user

definitions:
  Tenant:
    type: object
    properties:
      portalName:
        type: string
        description: Tenant portal name.
      domainName:
        type: string
        description: Tenant domain name.
      supporter:
        type: string
        description: Tenant supporter name.
      supporterEmail:
        type: string
        description: Tenant supporter email.
      createdAt:
        type: string
        description: Tenant created time, ISO data format, like '2018-08-12T20:17:46.384Z'.

  LoginRes:
    type: object
    properties:
      user:
        type: object
        items:
          - $ref: '#/definitions/User'
      tenant:
        type: object
        items:
          - $ref: '#/definitions/Tenant'    
      token:
        type: string
        description: Granted authentication token.

  User:
    type: object
    properties:
      tenantId:
        type: string
        description: Unique identifier representing a specific tenant.
      userId:
        type: string
        description: Unique identifier representing a specific user.
      displayName:
        type: string
        description: Username of user.
      firstName:
        type: string
        description: First name of user.
      lastName:
        type: string
        description: Last name of user.
      avatar:
        type: string
        description: Avatar of user.
      email:
        type: string
        description: Email of user.
      company:
        type: string
        description: Company of user.
      department:
        type: string
        description: Department of user.
      employeeId:
        type: string
        description: Employee Id of user.
      phone:
        type: string
        description: Phone of user.
      status:
        type: string
        description: Enable Status of user.
      data:
        type: object
        description: Metadata of user.
      loginAt:
        type: string
        description: User last login time, ISO data format, like '2018-08-12T20:17:46.384Z'.
      passwordExpireAt:
        type: string
        description: Last change password time, ISO data format, like '2018-08-12T20:17:46.384Z'.
      role:
        type: array
        description: List of role which contains the user.
        items:
          '$ref': '#/definitions/Role'

externalDocs:
  url: 'https://#'
  x-mocks:
    LoginRes:
      {
        "user":
          {
            "tenantId": "65af94c4-07e4-43d7-abad-3cb5f295550b",
            "userId": "916b3c8b-8c61-46a3-8751-e1bc4ddf80f1",
            "displayName": "Ellen Woods",
            "firstName": "Ellen",
            "lastName": "Woods",
            "avatar": "https://www.moxa.com/images/avatar/916b3c8b-8c61-46a3-8751-e1bc4ddf80f1.jpg",
            "email": "ellen@moxa.com",
            "company": "MOXA Inc.",
            "department": "Department",
            "employeeId": "123",
            "phone": "02-89191230",
            "loginAt": "2018-08-12T20:17:46.384Z",
            "passwordExpireAt": "2019-01-22T08:02:49:089Z",
            "data": 
              {
                "CUSTOM_FIELD": "CUSTOM_VALUE"
              },
            "role": {
              "admin": true,
              "id": 1,
              "name": "Administrator",
              "permission": [
                {
                  "id": 1,
                  "name": "User & Role management",
                  "value": 1
                },
                {
                  "id": 2,
                  "name": "Device register",
                  "value": 1
                },
                {
                  "id": 3,
                  "name": "Device grouping",
                  "value": 1
                },
                {
                  "id": 4,
                  "name": "View device information",
                  "value": 1
                },
                {
                  "id": 5,
                  "name": "Full manage device",
                  "value": 1
                }
              ]
            }
          },
        "tenant":
        {
          "createdAt": "2019-03-17T15:49:12.421655Z",
          "domainName": "tenant-dev",
          "portalName": "ISS",
          "supporter": "owen",
          "supporterEmail": "owen@moxa.com"
        },  
        "token": "USER_TOKEN"
      }

          