swagger: '2.0'

info:
  version: 0.0.2
  title: ThingsPro Tenant Portal RESTful API reference
basePath: '/api/v1'
schemes:
  - http
  - https
produces:
  - application/json

tags:
  - name: login
    description: Handles login/logout operation

paths:
  '/login':
    post:
      description: user login
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              username:
                type: string
                example: 'moxa'
              password:
                type: string
                example: '12345678'
      responses:
        200:
          description: Return user and token data
          schema:
            $ref: '#/definitions/LoginRes'
          examples: { 'application/json': { $ref: '#/externalDocs/x-mocks/LoginRes' } }
      tags:
        - login

  '/logout':
    post:
      description: user logout
      responses:
        200:
          description: user logout
      tags:
        - logout

definitions:
  LoginRes:
    type: object
    properties:
      user:
        type: object
        items:
          - $ref: '#/definitions/User' 
      token:
        type: string
        description: Granted authentication token.

externalDocs:
  url: '#'
  x-mocks:
    LoginRes:
      {
        "user":
          {
            "tenantId": "65af94c4-07e4-43d7-abad-3cb5f295550b",
            "userId": "916b3c8b-8c61-46a3-8751-e1bc4ddf80f1",
            "displayName": "Ellen Woods",
            "firstName": "Ellen",
            "lastName": "Woods",
            "avatar": "https://thingspro9dev4system.blob.core.windows.net/images/avatar/916b3c8b-8c61-46a3-8751-e1bc4ddf80f1.jpg",
            "email": "ellen@moxa.com",
            "company": "MOXA Inc.",
            "department": "Department",
            "employeeId": "123",
            "phone": "02-89191230",
            "loginAt": "2018-08-12T20:17:46.384Z",
            "data": 
              {
                "CUSTOM_FIELD": "CUSTOM_VALUE"
              },
            "tenant": {
              "permission": [
                { "id": 1, "name": "User/Role management", "value": 2 },
                { "id": 2, "name": "Device register/grouping", "value": 2 }
              ]
            },
            "groupList": [
              { 
                "groupId": 1, 
                "groupName": "All devices", 
                "permission": [
                  { "id": 3, "name": "View device information", "value": 2 },
                  { "id": 4, "name": "Full manage device", "value": 1 }
                ]
              },
              { 
                "groupId": 2, 
                "groupName": "North section", 
                "permission": [
                  { "id": 3, "name": "View device information", "value": 2 },
                  { "id": 4, "name": "Full manage device", "value": 1 }
                ]
              }
            ],
            "roleList": [
              {
                "id": 2,
                "name": "Device Register",
                "type": "tenant"
              }
            ]
          },
        "token": "USER_TOKEN"
      }
