swagger: '2.0'

info:
  version: 0.0.2
  title: ThingsPro Tenant Portal RESTful API reference
basePath: '/api/v1'
schemes:
  - http
  - https
produces:
  - application/json

tags:
  - name: permission
    description: Handles permission field data

paths:
  '/permissions':
    get:
      description: Get all permission field data
      responses:
        '200':
          description: success
          schema:
            type: array
            items:
              $ref: '#/definitions/Permission'
          examples: { 'application/json': { $ref: '#/externalDocs/x-mocks/PermissionList' } }
      tags:
        - permission

definitions:
  Permission:
    title: Permission
    type: object
    properties:
      permissionId:
        type: integer
        description: Unique identifier representing a specific user.
      type:
        type: string
        description: Naming of permission group type
        enum: [tenant, group]
      permissionName:
        type: string
        description: Name of permission.
      description:
        type: string
        description: Description of permission.
  PermissionUnion:
    type: object
    properties:
      permissionId:
        type: integer
        description: Unique identifier representing a specific user.
      value:
        type: string
        description: Attribute of Permission, 0 is cannot view/edit, 1 is can view but cannot edit, 2 is can view and edit
      permissionName:
        type: string
        description: Name of permission.

externalDocs:
  url: 'http://#'
  x-mocks:
    PermissionList:
      [
        { "permissionId": 1, "type": "tenant", "permissionName": "User/Role management", "description": "User/Role management" },
        { "permissionId": 2, "type": "tenant", "permissionName": "Device register/grouping", "description": "Device register/grouping" },
        { "permissionId": 3, "type": "group", "permissionName": "View device information", "description": "View device information" },
        { "permissionId": 4, "type": "group", "permissionName": "Full manage device", "description": "Full manage device" }
      ]
      