swagger: '2.0'

info:
  version: 0.0.2
  title: ThingsPro Tenant Portal RESTful API reference
basePath: '/api/v1'
schemes:
  - http
  - https
produces:
  - application/json

tags:
  - name: permission
    description: Handles permission field data

paths:
  '/permission':
    get:
      description: Get all permission field data
      responses:
        '200':
          description: success
          schema:
            type: array
            items:
              $ref: '#/definitions/Permission'
          examples: { 'application/json': { $ref: '#/externalDocs/x-mocks/PermissionList' } }
      tags:
        - permission

definitions:
  Permission:
    title: Permission
    required:
      - permissionId
      - value
    type: object
    properties:
      permissionId:
        type: integer
        description: Unique identifier representing a specific user.
      value:
        type: integer
        description: Attribute of Permission, 0 is cannot view/edit, 1 is can view but cannot edit, 2 is can view and edit
      name:
        type: string
        description: Name of permission.
      description:
        type: string
        description: Description of permission.

externalDocs:
  url: 'http://#'
  x-mocks:
    PermissionList:
      {
        "tenant": {
          "name": "Tenant administrator",
          "permissionList": [
            { "permissionId": 1, "value": 2, "name": "User/Role management", "description": "User/Role management" },
            { "permissionId": 2, "value": 2, "name": "Device register/grouping", "description": "Device register/grouping" }
          ]
        },
        "device": {
          "name": "Device operation",
          "permissionList": [
            { "permissionId": 1, "value": 2, "name": "View device information", "description": "View device information" },
            { "permissionId": 2, "value": 1, "name": "Full manage device", "description": "Full manage device" }
          ]
        }
      }