swagger: '2.0'

info:
  version: 0.0.0
  title: ThingsPro Tenant Portal RESTful API reference
basePath: '/api/v1'
schemes:
  - http
  - https
produces:
  - application/json

tags:
  - name: role
    description: Handles role field data

paths:
  /roles:
    get:
      description: Get all roles data
      tags:
        - role
      responses:
        200:
          description: An array of role
          schema:
            type: array
            items:
              $ref: '#/definitions/RolePermission'
            example: 
              $ref: '#/externalDocs/x-mocks/RoleList'
    post:
      description: Create a new role.
      tags:
        - role
      parameters:
        - name: body
          in: body
          description: ''
          required: true
          schema:
            type: object
            items:
              $ref: '#/definitions/RoleCreate'
            example:
              $ref: '#/externalDocs/x-mocks/RoleCreate'  

      responses:
        201:
          description: Create role successfully
          schema:
            type: object
            items:
              $ref: '#/definitions/Role'
            example: 
              $ref: '#/externalDocs/x-mocks/Role'

  /roles/{id}:
    parameters:
      - name: id
        in: path
        description: Role unique identifier
        required: true
        type: string
    get:
      description: Return role data with given ID
      tags:
        - role
      responses:
        200:
          description: An Object of the role
          schema:
            type: object
            items:
              $ref: '#/definitions/Role'
            example: 
              $ref: '#/externalDocs/x-mocks/Role'
    put:
      description: Return updated user data with given ID
      tags:
        - role
      parameters:
        - name: body
          in: body
          description: Information of role
          required: true
          schema:
            type: object
            items:
              $ref: '#/definitions/RoleCreate'
            example:
              $ref: '#/externalDocs/x-mocks/RoleCreate'  
      responses:
        200:
          description: An Object of the role
          schema:
            type: object
            items:
              $ref: '#/definitions/Role'
            example: 
              $ref: '#/externalDocs/x-mocks/Role'
    delete:
      description: Delete role with given ID
      tags:
        - role
      responses:
        204:
          description: success

  /roles/{id}/users:
    get:
      description: Get role users
      tags:
        - role
      parameters:
        - name: id
          in: path
          description: Role ID
          required: true
          type: string
        - name: name
          in: query
          description: Filter the user list by user name
          required: false
          type: string
        - name: email
          in: query
          description: Filter the user list by email
          required: false
          type: string
        - name: limit
          in: query
          description: max return users count (default is 100 and max is 1000)
          required: false
          type: integer
        - name: offset
          in: query
          description: offset
          required: false
          type: integer
      responses:
        200:
          description: An Object of the user
          schema:
            type: object
            items:
              $ref: '#/definitions/RoleUser'
            example: 
              $ref: '#/externalDocs/x-mocks/RoleUserList'
    put:
      description: Update users of role
      tags:
        - role
      parameters:
        - name: id
          in: path
          description: Role ID
          required: true
          type: string
        - name: body
          in: body
          description: Information of role
          required: true
          schema:
            type: array
            items:
              type: string
            description: user id list
            example:
              $ref: '#/externalDocs/x-mocks/UuidList'  
      responses:
        200:
          description: An Object of the user
          schema:
            type: array
            items:
              $ref: '#/definitions/RoleUserCreate'
            example:
              $ref: '#/externalDocs/x-mocks/RoleUserResponse'

  /roles/{id}/unassign:
    get:
      description: Get unassign users
      tags:
        - role
      parameters:
        - name: id
          in: path
          description: Role ID
          required: true
          type: string
        - name: keyword
          in: query
          description: Filter the user name & email by keyword
          required: false
          type: string
        - name: limit
          in: query
          description: max return users count (default is 100 and max is 1000)
          required: false
          type: integer
        - name: offset
          in: query
          description: offset
          required: false
          type: integer
      responses:
        200:
          description: An Object of the user
          schema:
            type: array
            items:
              $ref: '#/definitions/RoleUser'
            example: 
              $ref: '#/externalDocs/x-mocks/RoleUserList'

  /roles/{id}/duplicate:
    post:
      description: Duplicate a new role
      tags:
        - role
      parameters:
        - name: id
          in: path
          description: Role ID
          required: true
          type: string
      responses:
        201:
          description: Create role successfully
          schema:
            type: object
            items:
              $ref: '#/definitions/Role'
            example: 
              $ref: '#/externalDocs/x-mocks/Role'

definitions:
  Role:
    type: object
    properties:
      id:
        type: integer
        description: Unique identifier representing a specific user.
      name:
        type: string
        description: Name of role.
      description:
        type: string
        description: Description of role.
      admin:
        type: boolean
        description: Admin role.

  RolePermission:
    type: object
    properties:
      id:
        type: integer
        description: Role ID.
      name:
        type: string
        description: Name of role.
      description:
        type: string
        description: Description of role.
      admin:
        type: boolean
        description: Admin role.
      count:
        type: integer
        description: User count of role
      permission:
        type: array
        items:
          type: object
          items:
            - $ref: '#/definitions/Permission'

  RoleCreate:
    type: object
    properties:
      name:
        type: string
        description: Name of role.
        maxLength: 30
      description:
        type: string
        description: Description of role.
        maxLength: 200
      permission:
        type: array
        items:
          type: object
          items:
            - $ref: '#/definitions/Permission'

  RoleUser:
    type: object
    properties:
      userId:
        type: string
        description: Unique identifier representing a specific user.
      displayName:
        type: string
        description: Username of user.
      avatar:
        type: string
        description: Avatar of user.
      email:
        type: string
        description: Email of user.

  RoleUserCreate:
    type: object
    properties:
      users:
        type: object
        items:
          type: string

externalDocs:
  url: 'http://#'
  x-mocks:
    Role:
      {
        "id": 19,
        "name": "test role 2",
        "description": "test role 2",
        "admin": false,
        "permission": [
          {
            "id": 1,
            "name": "User/Role management",
            "description": "User/Role management",
            "type": 1,
            "value": 0
          },
          {
            "id": 2,
            "name": "Device register",
            "description": "Device register",
            "type": 1,
            "value": 1
          }
        ]
      }
    RoleCreate:
      {
        "name": "Device Register",
        "description": "Device Register",
        "permission": [
          {
            "id": 1,
            "name": "User/Role management",
            "description": "User/Role management",
            "type": 1,
            "value": 0
          },
          {
            "id": 2,
            "name": "Device register",
            "description": "Device register",
            "type": 1,
            "value": 1
          }
        ]
      }
    RolePermission:
      {
        "id": 2,
        "name": "Device Register",
        "count": 3,
        "description": "Device Register",
        "admin": false,
        "permission": [
          {
            "id": 1,
            "name": "User/Role management",
            "description": "User/Role management",
            "type": 1,
            "value": 0
          },
          {
            "id": 2,
            "name": "Device register",
            "description": "Device register",
            "type": 1,
            "value": 1
          }
        ]
      }
    RoleList: 
      {
        "data": [
          {
            "id": 1,
            "name": "Administrator",
            "description": "Administrator",
            "admin": true,
            "count": 1,
            "permission": [
              {
                "id": 1,
                "name": "User/Role management",
                "description": "User/Role management",
                "type": 1,
                "value": 1
              },
              {
                "id": 2,
                "name": "Device register",
                "description": "Device register",
                "type": 1,
                "value": 1
              }
            ]
          },
          {
            "id": 2,
            "name": "Device Register",
            "description": "Device Register",
            "admin": false,
            "count": 3,
            "permission": [
              {
                "id": 1,
                "name": "User/Role management",
                "description": "User/Role management",
                "type": 1,
                "value": 0
              },
              {
                "id": 2,
                "name": "Device register",
                "description": "Device register",
                "type": 1,
                "value": 1
              }
            ]
          },
          {
            "id": 5,
            "name": "Full device manager",
            "description": "Full device manager",
            "admin": false,
            "count": 3,
            "permission": [
              {
                "id": 3,
                "name": "View device information",
                "description": "View device information",
                "type": 2,
                "value": 1
              },
              {
                "id": 4,
                "name": "Full manage device",
                "description": "Full manage device",
                "type": 2,
                "value": 1
              }
            ]
          }
        ]
      }
    RoleUserList:
      {
        "count": 3,
        "data": [
          {
            "userId": "aedd319a-3d21-4ba5-aee8-0b8ec2806b09",
            "avatar": "",
            "displayName": "Owen Kao",
            "email": "owenyc.kao@moxa.com"
          },
          {
            "userId": "6df5d905-e19c-4cc8-b963-88707c6fa7f3",
            "avatar": "",
            "displayName": "Edie Lin",
            "email": "ediejy.lin@moxa.com"
          },
          {
            "userId": "7dc93587-5444-48bf-a196-da811c39959d",
            "avatar": "https://thingspro9dev4system.blob.core.windows.net/images/avatar/7dc93587-5444-48bf-a196-da811c39959d.jpg",
            "displayName": "Cain Chen",
            "email": "cainhc.chen@moxa.com"
          }
        ],
        "limit": 100,
        "offset": 0
      }
    RoleUserCreate:
      {
        users: [
          "6df5d905-e19c-4cc8-b963-88707c6fa7f3"
        ]
      }  
    UuidList:
      [
        "ed31872d-b57e-4c94-a989-c2782c0d3fe7"
      ]
    RoleUserResponse:
      {
        "data": [
          {
            "userId": "6df5d905-e19c-4cc8-b963-88707c6fa7f3",
            "displayName": "Edie Lin",
            "avatar": "",
            "email": "ediejy.lin@moxa.com"
          },
          {
            "userId": "7dc93587-5444-48bf-a196-da811c39959d",
            "displayName": "Cain Chen",
            "avatar": "https://thingspro9dev4system.blob.core.windows.net/images/avatar/7dc93587-5444-48bf-a196-da811c39959d.jpg",
            "email": "cainhc.chen@moxa.com"
          }
        ]
      }