swagger: '2.0'

info:
  version: 0.0.2
  title: ThingsPro Tenant Portal RESTful API reference
basePath: '/api/v1'
schemes:
  - http
  - https
produces:
  - application/json

tags:
  - name: role
    description: Handles role field data

paths:
  /roles:
    get:
      description: Get all roles data
      tags:
        - role
      responses:
        200:
          description: An array of role
          schema:
            type: array
            items:
              $ref: '#/definitions/RolePermission'
          examples: { 'application/json': { $ref: '#/externalDocs/x-mocks/RoleList' } }
    post:
      description: Create a new role.
      tags:
        - role
      parameters:
        - name: body
          in: body
          description: ''
          required: true
          schema:
            $ref: '#/definitions/RoleCreate'
      responses:
        201:
          description: Create role successfully
          schema:
            type: object
            items:
              $ref: '#/definitions/Role'
          examples: { 'application/json': { $ref: '#/externalDocs/x-mocks/Role' } }

  /roles/{id}:
    parameters:
      - name: id
        in: path
        description: Role unique identifier
        required: true
        type: string
    get:
      description: Return role data with given ID
      tags:
        - role
      responses:
        200:
          description: An Object of the role
          schema:
            type: object
            items:
              $ref: '#/definitions/RolePermission'
          examples: { 'application/json': { $ref: '#/externalDocs/x-mocks/RolePermission' } }
    put:
      description: Return updated user data with given ID
      tags:
        - role
      parameters:
        - name: body
          in: body
          description: Information of role
          required: true
          schema:
            $ref: '#/definitions/RoleUpdate'
      responses:
        200:
          description: An Object of the role
          schema:
            type: object
            items:
              $ref: '#/definitions/Role'
          examples: { 'application/json': { $ref: '#/externalDocs/x-mocks/Role' } }
    delete:
      description: Delete role with given ID
      tags:
        - role
      responses:
        204:
          description: success

definitions:
  Role:
    type: object
    properties:
      id:
        type: integer
        description: Unique identifier representing a specific user.
      name:
        type: string
        description: Name of role.
      type:
        type: integer
        description: Role type.
      description:
        type: string
        description: Description of role.
      enabled:
        type: boolean
        description: Status of role.

  RolePermission:
    type: object
    properties:
      id:
        type: integer
        description: Role ID.
      name:
        type: string
        description: Name of role.
      type:
        type: integer
        description: Role type.
      description:
        type: string
        description: Description of role.
      enabled:
        type: boolean
        description: Status of role.
      count:
        type: integer
        description: User count of role
      permission:
        type: array
        items:
          type: object
          items:
            - $ref: '#/definitions/Permission'

  RoleCreate:
    type: object
    properties:
      name:
        type: string
        description: Name of role.
        maxLength: 30
      description:
        type: string
        description: Description of role.
        maxLength: 200
      type:
        type: integer
        description: Role type.
      permission:
        type: array
        items:
          type: object
          items:
            - $ref: '#/definitions/Permission'

  RoleUpdate:
    type: object
    properties:
      name:
        type: string
        description: Name of role.
        maxLength: 30
      description:
        type: string
        description: Description of role.
        maxLength: 200
      permission:
        type: array
        items:
          type: object
          items:
            - $ref: '#/definitions/Permission'

  Permission:
    type: object
    properties:
      id:
        type: integer
        description: Unique identifier representing a specific user.
      name:
        type: string
        description: Name of permission.
      type:
        type: integer
        description: Naming of permission group type
        enum: [1, 2]
      description:
        type: string
        description: Description of permission.
      value:
        type: integer
        description: Value of permission

externalDocs:
  url: 'http://#'
  x-mocks:
    Role:
      {
        "id": 19,
        "name": "test role 2",
        "type": 1,
        "description": "test role 2",
        "enabled": true
      }
    RolePermission:
      {
        "id": 2,
        "name": "Device Register",
        "count": 3,
        "description": "Device Register",
        "enabled": true,
        "permission": [
          {
            "id": 1,
            "name": "User/Role management",
            "type": 1,
            "description": "User/Role management",
            "value": 0
          },
          {
            "id": 2,
            "name": "Device register/grouping",
            "type": 1,
            "description": "Device register/grouping",
            "value": 1
          }
        ],
        "type": 1
      }
    RoleList: 
      {
        "data": [
          {
            "id": 1,
            "name": "Administrator",
            "type": 0,
            "description": "Administrator",
            "enabled": true,
            "count": 1,
            "permission": [
              {
                "id": 1,
                "name": "User/Role management",
                "type": 1,
                "description": "User/Role management",
                "value": 1
              },
              {
                "id": 2,
                "name": "Device register/grouping",
                "type": 1,
                "description": "Device register/grouping",
                "value": 1
              }
            ]
          },
          {
            "id": 2,
            "name": "Device Register",
            "type": 1,
            "description": "Device Register",
            "enabled": true,
            "count": 3,
            "permission": [
              {
                "id": 1,
                "name": "User/Role management",
                "type": 1,
                "description": "User/Role management",
                "value": 0
              },
              {
                "id": 2,
                "name": "Device register/grouping",
                "type": 1,
                "description": "Device register/grouping",
                "value": 1
              }
            ]
          },
          {
            "id": 5,
            "name": "Full device manager",
            "type": 2,
            "description": "Full device manager",
            "enabled": true,
            "count": 3,
            "permission": [
                {
                    "description": "View device information",
                    "id": 3,
                    "name": "View device information",
                    "type": 2,
                    "value": 1
                },
                {
                    "description": "Full manage device",
                    "id": 4,
                    "name": "Full manage device",
                    "type": 2,
                    "value": 1
                }
            ]
          }
        ]
      }