swagger: '2.0'

info:
  version: 0.0.1
  title: ThingsPro Tenant Portal RESTful API reference
basePath: '/tenant-api/v1'
schemes:
  - http
  - https
produces:
  - application/json

tags:
  - name: login
    description: Handles login/logout operation

paths:
  '/login':
    post:
      description: user login
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              username:
                type: string
                example: 'moxa'
              password:
                type: string
                example: '12345678'
      responses:
        200:
          description: Return user and token data
          schema:
            $ref: '#/definitions/LoginRes'
          examples: { 'application/json': { $ref: '#/externalDocs/x-mocks/LoginRes' } }
      tags:
        - login

  '/logout':
    post:
      description: user logout
      responses:
        200:
          description: user logout
      tags:
        - logout

definitions:
  LoginRes:
    type: object
    properties:
      user:
        type: object
        items:
          - $ref: '#/definitions/User'
      role:
        type: object
        items:
          - $ref: '#/definitions/Role'    
      token:
        type: string
        description: Granted authentication token.

externalDocs:
  url: '#'
  x-mocks:
    LoginRes:
      {
        user:
          {
            "userId": 1,
            "tenantId": "65af94c4-07e4-43d7-abad-3cb5f295550b",
            "username": "username",
            "firstName": "firstName",
            "lastName": "lastName",
            "email": "moxa@moxa.com",
            "role":
              {
                "id": 1,
                "name": "root",
                "permissions":
                  [
                    { "id": 1, "value": 2, "name": "DM", "description": "xxxxx" },
                    { "id": 2, "value": 2, "name": "account", "description": "xxxxx" }
                  ]
              },
            "phone": "1234567890",        
            "loginAt": "2018-08-12T20:17:46.384Z",
            "data": 
              {
                "CUSTOM_FIELD": "CUSTOM_VALUE"
              }
          },
        token: "USER_TOKEN"
      }
