openapi: '3.0.0'

x-tagGroups:
  - name: Device Configuration API
    tags:
      - general
      - user
      - project
      - profile
      - device
      - deviceOperation

info:
  version: '1.1.0'
  title: 'Device Configuration APIs'
  description: 'Device Configuration APIs'

servers:
  - url: https://127.0.0.1/api/v1
      
components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT    # optional, arbitrary value for documentation purposes

security:
  - bearerAuth: []
  
