---
swagger: '2.0'

info:
  version: 2.1.0
  title: ThingsPro Edge RESTful API reference
basePath: "/api/v1"
schemes:
- http
- https
produces:
- application/json
securityDefinitions:
  mx-api-token:
    type: apiKey
    name: mx-api-token
    in: header
    description: ThingsPro RESTful API token, The token should be created on web console.

tags:
- name: program
  description: Provides the user program service

paths:
  "/system/programs":
    get:
      description: Get all custom programs
      responses:
        '200':
          description: success
          schema:
            "$ref": "#/definitions/Programs"
            example:
            - id: 1
              name: my-user-program
              enable: true
              startMode: period
              args: "--url http://localhost"
              period: 12
              timeout: 1
              lastExcutedTime: '2017-01-09T06:46:01.181Z'
              fileExist: true
              logsExist: true
            - id: 2
              name: my-user-program-2
              enable: true
              startMode: period
              args: "--url http://localhost"
              period: 10
              timeout: 1
              lastExcutedTime: '2017-01-09T06:46:01.181Z'
              fileExist: false
              logsExist: false
      tags:
      - program
      security:
      - mx-api-token: []
    post:
      description: Create a new Program
      parameters:
      - name: body
        in: body
        description: ''
        required: true
        schema:
          "$ref": "#/definitions/UpdateProgram"
      responses:
        '200':
          description: OK
          schema:
            "$ref": "#/definitions/Program"
            example:
              id: 1
              name: my-user-program
              enable: true
              startMode: period
              args: "--url http://localhost"
              period: 10
              timeout: 1
              lastExcutedTime: '2017-01-09T06:46:01.181Z'
              fileExist: true
              logsExist: true
              file:
                url: http://remote-download-url/file.tar.gz
                headers:
                  authorization: xxxxxxx
      tags:
      - program
      security:
      - mx-api-token: []
    delete:
      description: Delete Programs
      parameters:
      - name: body
        in: body
        description: ''
        required: true
        schema:
          type: array
          items:
            type: number
            description: IDs
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              count:
                type: number
                description: Affected number of rows
            example:
              count: 1
      tags:
      - program
      security:
      - mx-api-token: []
  "/system/programs/{id}":
    parameters:
    - name: id
      in: path
      type: integer
      required: true
    get:
      description: Get program by given id
      responses:
        '200':
          description: success
          schema:
            "$ref": "#/definitions/Program"
            example:
              id: 1
              name: my-user-program
              enable: true
              startMode: period
              args: "--url http://localhost"
              period: 10
              timeout: 1
              lastExcutedTime: '2017-01-09T06:46:01.181Z'
              fileExist: true
              logsExist: true
              file:
                url: http://remote-download-url/file.tar.gz
                headers:
                  authorization: xxxxxxx
      tags:
      - program
      security:
      - mx-api-token: []
    put:
      description: Update program settings by given id
      parameters:
      - name: body
        in: body
        description: ''
        required: true
        schema:
          "$ref": "#/definitions/UpdateProgram"
      responses:
        '200':
          description: OK
          schema:
            "$ref": "#/definitions/Program"
            example:
              id: 1
              name: my-user-program
              enable: true
              startMode: period
              args: "--url http://localhost"
              period: 10
              timeout: 1
              lastExcutedTime: '2017-01-09T06:46:01.181Z'
              fileExist: true
              logsExist: true
              file:
                url: http://remote-download-url/file.tar.gz
                headers:
                  authorization: xxxxxxx
      tags:
      - program
      security:
      - mx-api-token: []
  "/system/programs/{id}/file":
    parameters:
    - name: id
      in: path
      type: integer
      required: true
    post:
      description: Download program by given id
      responses:
        '200':
          description: success
          schema:
            "$ref": "#/definitions/Download"
            example:
              url: http://download/file
      tags:
      - program
      security:
      - mx-api-token: []
  "/system/programs/{id}/logs":
    parameters:
    - name: id
      in: path
      type: integer
      required: true
    post:
      description: Download logs by given id
      responses:
        '200':
          description: success
      tags:
      - program
      security:
      - mx-api-token: []

definitions:
  Programs:
    type: array
    items:
      "$ref": "#/definitions/Program"
    example:
      id: 1
      name: my-user-program
      enable: true
      startMode: period
      args: "--url http://localhost"
      period: 10
      timeout: 1
      lastExcutedTime: '2017-01-09T06:46:01.181Z'
      fileExist: true
      logsExist: true
      file:
        url: http://remote-download-url/file.tar.gz
        headers:
          authorization: xxxxxxx
  Program:
    type: object
    properties:
      id:
        type: number
        readOnly: true
        description: ID of this program
      name:
        type: string
        description: Program name
        maxLength: 255
        minLength: 2
        pattern: "^[A-Za-z0-9_-]+$"
      enable:
        type: boolean
        description: Enable program
      startMode:
        type: string
        description: Program start mode
        enum:
        - boot
        - period
      args:
        type: string
        description: arguments
        minLength: 0
        maxLength: 2048
      period:
        type: number
        description: Period execution time (unit minutes)
        minimum: 0
        maximum: 65535
      timeout:
        type: number
        description: execution timeout (in seconds, 0 means no timeout)
        minimum: 0
        maximum: 65535
      lastExcutedTime:
        type: string
        format: date-time
        readOnly: true
        description: Last program has been excuted time (iso 8601)
      fileExist:
        type: boolean
        readOnly: true
        description: User program uploaded or not
      logsExist:
        type: boolean
        readOnly: true
        description: Logs avaliable for download or not
    example:
      id: 1
      name: my-user-program
      enable: true
      startMode: period
      args: "--url http://localhost"
      period: 10
      timeout: 1
      lastExcutedTime: '2017-01-09T06:46:01.181Z'
      fileExist: true
      logsExist: true
      file:
        url: http://remote-download-url/file.tar.gz
        headers:
          authorization: xxxxxxx
  UpdateProgram:
    allOf:
    - "$ref": "#/definitions/Program"
    - "$ref": "#/definitions/Upload"
  Upload:
    type: object
    properties:
      file:
        type: object
        properties:
          url:
            type: string
            description: Download link
          header:
            type: object
            description: Headers for download link
  Download:
    required:
    - url
    properties:
      url:
        type: string
      headers:
        type: object
    example:
      url: http://download/file
