---
swagger: '2.0'

info:
  version: 2.1.0
  title: ThingsPro Edge RESTful API reference
basePath: "/api/v1"
schemes:
- http
- https
produces:
- application/json
securityDefinitions:
  mx-api-token:
    type: apiKey
    name: mx-api-token
    in: header
    description: ThingsPro RESTful API token, The token should be created on web console.

tags:
- name: route
  description: Handles the routing table

paths:
  "/network/routes/default":
    get:
      summary: Current Default Route and priority list
      description: |
        The system returns the current default route information and default
        route priority list.
      responses:
        '200':
          description: Default Route
          schema:
            "$ref": "#/definitions/DefaultRoute"
            example:
              interface: eth0
              gateway: 192.168.3.254
              priorityList:
              - wwan0
              - eth0
      tags:
      - route
      security:
      - mx-api-token: []
    put:
      parameters:
      - name: body
        in: body
        required: true
        schema:
          "$ref": "#/definitions/DefaultRoute"
      summary: Update Default Route Setting
      description: Update the default route list.
      responses:
        '200':
          description: OK
          schema:
            "$ref": "#/definitions/DefaultRoute"
            example:
              priorityList:
              - wwan0
              - eth0
      tags:
      - route
      security:
      - mx-api-token: []

definitions:
  DefaultRoute:
    title: DefaultRoute
    required:
    - interface
    properties:
      interface:
        type: string
        description: Indicate the interface name (readonly).
      gateway:
        type: string
        pattern: "^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$"
        readOnly: true
        description: |
          Gateway is a router or a proxy server that routes between networks
          (readonly).
      priorityList:
        type: array
        items:
          description: interface for default route
          type: string
          pattern: "[A-Za-z0-9_-]+"
          minLength: 2
          maxLength: 255
    example:
      interface: eth0
      gateway: 192.168.3.254
      priorityList:
      - wwan0
      - eth0
