---
swagger: '2.0'

tags:
- $ref: "./project.yaml#/tags"
- $ref: "./projectModelProfile.yaml#/tags"

paths:
- $ref: "./project.yaml#/paths"
- $ref: "./projectModelProfile.yaml#/paths"

definitions:
- $ref: "./project.yaml#/definitions"
- $ref: "./projectModelProfile.yaml#/definitions"

