swagger: '2.0'

info:
  version: 0.0.1
  title: ThingsPro Tenant Portal RESTful API reference
basePath: '/api/v1'
schemes:
  - http
  - https
produces:
  - application/json
tags:
  - name: app
    description: Handles app data

paths:
  /apps:
    get:
      parameters:
        - name: appName
          in: query
          description: Filter the app list by appName
          required: false
          type: string
        - name: cpuArch
          in: query
          description: Filter the app list by cpuArch
          required: false
          type: string
        - name: categoryId
          in: query
          description: Filter the app list by categoryId
          required: false
          type: string
        - name: categoryName
          in: query
          description: Filter the app list by categoryName
          required: false
          type: string
        - name: order
          in: query
          description: Ordering the filter app list, default is asc
          required: false
          type: string  
          enum:
          - desc
          - asc
        - name: sort
          in: query
          description: Sort the app list by specific ordering, default is sort by 'appId'
          required: false
          type: string
          enum:
          - appId
          - appName
          - categoryId
          - categoryName
        - name: limit
          in: query
          description: max return app count (default is 100 and max is 1000)
          required: false
          type: integer  
        - name: offset
          in: query
          description: offset
          required: false
          type: integer             
      description: Get all app field data
      responses:
        200:
          description: An array of app
          schema:
            type: array
            items:
              $ref: '#/definitions/App'
            example: 
              $ref: '#/externalDocs/x-mocks/AppList'
      tags:
        - app

  /apps/{app_version_id}:
    parameters:
      - name: app_version_id
        in: path
        description: app version id
        required: true
        type: string
    get:
      description: Return app data & version info with given ID
      tags:
        - app
      responses:
        200:
          description: An Object of the app
          schema:
            type: object
            items:
              $ref: '#/definitions/App'
            example: 
              $ref: '#/externalDocs/x-mocks/App'

  /apps/category:
    get:
      description: Get all category of app
      responses:
        200:
          description: An array of app category
          schema:
            type: array
            items:
              $ref: '#/definitions/AppCategory'
            example: 
              $ref: '#/externalDocs/x-mocks/AppCategoryList'
      tags:
        - app

definitions:
  App:
    type: object
    properties:
      appId:
        type: string
        description: Unique identifier representing a specific app.
      appName:
        type: string
        description: Name of app.
      cpuArch:
        type: string
        description: CPU Architecture.  
      description:
        type: string
        description: Description of app.  
      displayName:
        type: string
        description: Display Name of app.
      iconUrl:
        type: string
        description: The icon URL of app.
      downloadUrl:
        type: string
        description: The download URL of app.
      isTrialLicense:
        type: boolean
        description: Is trial license ?
      licenseStatement:
        type: string
        description: License Statement. ( e.g. Trial - 30 days )
      publishAt:
        type: string
        description: app publist time, ISO data format, like '2018-08-12T20:17:46.384Z'.
      publisher:
        type: string
        description: Publisher of app.
      trialPeriodInDay:
        type: string
        description: unknown.
      unitPrice:
        type: number
        description: Unit price of app.
      validAt:
        type: string
        description: App valid time, ISO data format, like '2018-08-12T20:17:46.384Z'.
      version:
        type: string
        description: App versoin.
      categoryList:
        type: array
        description: Category list.
        items:
          type: object
          items:
              $ref: '#/definitions/AppCategory'

  AppCategory:
    type: object
    properties:
      categoryId:
        type: integer
        description: Unique identifier representing a specific app category.
      categoryName:
        type: string
        description: Name of app category.
      type:
        type: string
        description: Type of app. e.g. edge
      description:
        type: integer
        description: Description of app category.  

externalDocs:
  url: 'http://#'
  x-mocks:
    App:
      {
        "appId": 1,
        "appVersionId": 21,
        "appName": "app-cloud",
        "categoryList": [
          {
            "categoryId": 3,
            "categoryName": "Intelligence",
            "description": "Intelligence",
            "type": "edge"
          }
        ],
        "cpuArch": "armhf",
        "description": "app-cloud",
        "displayName": "app-cloud",
        "iconUrl": "http://tenant-west-us.thingspro.io/images/edge-application/app-cloud/0.3.0-18/logo.png",
        "downloadUrl": "http://repo.moxa.online/static/v3/edge/builds/edge-app-cloud/18/app-cloud.3.0-18_armhf.mpkg",
        "isTrialLicense": true,
        "licenseStatement": "Trial - 30 days",
        "publishAt": "2018-09-27T06:54:14.203998+00:00Z",
        "publisher": "Moxa-ISD",
        "trialPeriodInDay": "",
        "unitPrice": "",
        "validAt": "2018-09-27T06:54:14.203998+00:00Z",
        "version": "0.3.0-18"
      }
    AppList:
      {
        "count": 5,
        "offset": 0,
        "limit": 100,
        "data": [
          {
            "appId": 1,
            "appName": "app-cloud",
            "appVersionId": 1,
            "categoryList": [
              {
                "categoryId": 2,
                "categoryName": "Cloud Connectivity",
                "description": "Cloud Connectivity",
                "type": "edge"
              }
            ],
            "cpuArch": "amd64",
            "description": "MOXA cloud client",
            "displayName": "cloud Client",
            "downloadUrl": "http://repo.moxa.online/static/v3/edge/builds/edge-app-cloud/24/app-cloud.5.0-24_amd64.mpkg",
            "iconUrl": "http://tenant-west-us.thingspro.io/images/edge-application/app-cloud/0.5.0-24/logo.png",
            "isTrialLicense": true,
            "licenseStatement": "Trial - 30 days",
            "publishAt": "2018-09-27T06:53:51.719756+00:00Z",
            "publisher": "Moxa-ISD",
            "trialPeriodInDay": "",
            "unitPrice": "",
            "validAt": "2018-09-27T06:53:51.719756+00:00Z",
            "version": "0.5.0-24"
          },
          {
            "appId": 4,
            "appName": "linuxdesktop",
            "appVersionId": 21,
            "categoryList": [
              {
                "categoryId": 3,
                "categoryName": "Intelligence",
                "description": "Intelligence",
                "type": "edge"
              }
            ],
            "cpuArch": "amd64",
            "description": "Linux Desktop",
            "displayName": "Linux Desktop",
            "downloadUrl": "http://repo.moxa.online/static/v3/edge/builds/edge-app-linuxdesktop/12/linuxdesktop_0.3.0-12_amd64.mpkg",
            "iconUrl": "http://tenant-west-us.thingspro.io/images/edge-application/linuxdesktop/0.3.0-12/logo.png",
            "isTrialLicense": "",
            "licenseStatement": "Trial - 30 days",
            "publishAt": "2018-10-16T06:22:04.373362+00:00Z",
            "publisher": "Moxa-ISD",
            "trialPeriodInDay": "",
            "unitPrice": "",
            "validAt": "2018-10-16T06:22:04.373362+00:00Z",
            "version": "0.3.0-12"
          }
        ]
      }
    AppCategoryList:
      {
        "data": [
          {
            "categoryId": 1,
            "categoryName": "Protocol",
            "description": "Protocol",
            "type": "edge"
          },
          {
            "categoryId": 2,
            "categoryName": "Cloud Connectivity",
            "description": "Cloud Connectivity",
            "type": "edge"
          },
          {
            "categoryId": 3,
            "categoryName": "Edge Computing",
            "description": "Edge Computing",
            "type": "edge"
          },
          {
            "categoryId": 4,
            "categoryName": "Others",
            "description": "Others",
            "type": "edge"
          }
        ]
      }