swagger: '2.0'

info:
  version: 0.0.0
  title: ThingsPro Server RESTful API reference
basePath: '/api/v1'
schemes:
  - http
  - https
produces:
  - application/json
securityDefinitions:
  mx-api-token:
    type: apiKey
    name: mx-api-token
    in: header
    description: ThingsPro RESTful API token, The token should be created on web console.

tags:
  - name: device
    description: Cloud Gateway management

paths:
  /devices:
    get:
      tags:
        - device
      security:
        - mx-api-token: []
      description: >-
        The Devices endpoint returns information about the *ThingsPro* gateway
        information.
      parameters:
        - name: offset
          in: query
          description: offset
          required: false
          type: number
          format: integer
        - name: limit
          in: query
          description: |
            max return devices count (default: 20)
          required: false
          type: number
          format: integer
        - name: uuid
          in: query
          description: |
            get uuid exactly match device
          required: false
          type: string
        - name: mac
          in: query
          description: |
            get mac exactly match device
          required: false
          type: string
        - name: serialNumber
          in: query
          description: |
            get serial number exactly match device
          required: false
          type: string        
        - name: query
          in: query
          description: |
            Query and filter device by keyword, 
            please encode query json object by urlencode, and append it on query parameter
            please refer definition of FilterDevice to get query object json format
            limit default is 20 and max is 1000
            The search key now support 'uuid, mac, displayName, serialNumber, defaultRoute, softwareVersion' 
            Each search value is wildcard, can just input partial value only
          required: false
          type: string
      responses:
        '200':
          description: An array of gateways
          schema:
            $ref: '#/definitions/DeviceList'
            example:
              $ref: '#/externalDocs/x-mocks/DeviceList'
    post:
      tags:
        - device
      security:
        - mx-api-token: []
      description: Create (register) a new device to ThingsPro Cloud Server.
      parameters:
        - name: body
          in: body
          description: ''
          required: true
          schema:
            $ref: '#/definitions/DeviceCreate'
      responses:
        '200':
          description: An array of gateways
          schema:
            type: array
            items:
              $ref: '#/definitions/Device'
            example:
              $ref: '#/externalDocs/x-mocks/DeviceCreateRes'
    delete:
      tags:
        - device
      security:
        - mx-api-token: []
      description: Delete (de-register) devices from ThingsPro Cloud Server.
      parameters:
        - name: body
          in: body
          description: Delete ids
          required: true
          schema:
            $ref: '#/definitions/DeviceUUIDs'
      responses:
        '200':
          description: success
  /devices/{uuid}':
    parameters:
      - name: uuid
        in: path
        description: Device unique identifier
        required: true
        type: string
    get:
      security:
        - mx-api-token: []
      tags:
        - device
      description: Return Device with given UUID
      responses:
        '200':
          description: An Object of the device
          schema:
            type: object
            items:
              $ref: '#/definitions/Device'
            example:
              $ref: '#/externalDocs/x-mocks/Device'
    delete:
      tags:
        - device
      security:
        - mx-api-token: []
      description: Delete Device with given UUID
      responses:
        '200':
          description: success

definitions:
  DeviceCreate:
    type: object
    properties:
      displayName:
        type: string
        description: Display name of device.
      mac:
        type: string
        description: MAC address of device.
      serialNumber:
        type: string
        description: Serial number of device.
  Device:
    type: object
    properties:
      uuid:
        type: string
        readOnly: true
        description: Unique identifier representing a specific device.
      description:
        type: string
        description: Description of device.
      displayName:
        type: string
        description: Display name of device.
      mac:
        type: string
        description: MAC address of device.
      iccId:
        type: string
        description: Cellular ICCID
      serialNumber:
        type: string
        description: Serial number of device.
      connection:
        type: object
        readOnly: true
        description: Device's latest connection status
      properties:
        type: object
        readOnly: true
        description: Device's latest system properties
        properties:
          aliasName:
            type: string
            description: Display name of device
          iccId:
            type: string
            description: Iccid of device
          modelName:
            type: string
            description:  Model name of device
          softwareVersion:
            type: string
            description: Firmware(software) version of device
          defaultRoute:
            type: string
            enum:
              - wwan0
              - wlan0
              - eth0
            description: Default route of device, wwan0 represents cellular, wlan0 represents wifi, eth0 represents ethernet
          gps:
            type: object
            properties:
              lat:
                type: number
                description: gps lat value
              lng:
                type: number
                description: gps lng value
          wifi:
            type: string
            enum:
              - connected
              - disconnected
              - auth_failed
            description: Default route of device, wwan0 represents cellular, wlan0 represents wifi, eth0 represents ethernet
          customProperties:
            type: object
            description: User custom defined properties
    example:
      $ref: '#/externalDocs/x-mocks/Device'
  DeviceList:
    type: object
    properties:
      count:
        type: number
        description: Total count of devices
      limit:
        type: number
        description: query limit number
      offset:
        type: number
        description: query offset number
      data:
        type: array
        items:
          $ref: '#/definitions/Device'
    example:
      $ref: '#/externalDocs/x-mocks/DeviceList'
  DeviceUUIDs:
    type: array
    items:
      type: string
      description: UUID of deivce
      example: ded6dd9e-49d9-485b-bac1-da0ca0ae9d70
  FilterDevice:
    type: object
    properties:
      limit:
        type: number
        description: query limit number
      offset:
        type: number
        description: query offset number
      keys:
        type: object
        description: query keyword
    example:
      $ref: '#/externalDocs/x-mocks/FilterDevice'

externalDocs:
  url: 'http://#'
  x-mocks:
    Device:
      uuid: ded6dd9e-49d9-485b-bac1-da0ca0ae9d70
      description: Temperature monitoring
      displayName: 'Gym tempture sensor #1'
      mac: 223344FFFF11
      iccId: 898600MFSSYYGXXXXXXP
      serialNumber: MOXA00000001
    DeviceCreateRes:
      uuid: ded6dd9e-49d9-485b-bac1-da0ca0ae9d70
      description: Temperature monitoring
      displayName: 'Gym tempture sensor #1'
      mac: 223344FFFF11
      iccId: 898600MFSSYYGXXXXXXP
      serialNumber: MOXA00000001
    DeviceList:
      count: 3
      data:
        - connection:
            createdAt: '2017-03-22T08:15:01.359380'
            deviceUUID: 2ad0fbb8-6f53-46ea-a10a-00b7b75145d3
            status: offline
          createdAt: '2017-03-21T03:01:10.175584'
          description: Device
          displayName: ThingsPro-changed
          mac: 223344FF8F51
          iccId: 898600MFSSYYGXXXXXXP
          serialNumber: MOXA00000001
          properties:
            aliasName: ThingsPro-changed
            createdAt: '2017-03-22T06:41:33.195046'
            deviceUUID: 2ad0fbb8-6f53-46ea-a10a-00b7b75145d3
            gps:
              lat: 0
              lng: 0
          updatedAt: '2017-03-22T06:19:58.475876'
          uuid: 2ad0fbb8-6f53-46ea-a10a-00b7b75145d3
        - connection:
            createdAt: '2017-03-10T01:55:41.097736'
            deviceUUID: 2730e69e-8d5a-4642-a7cf-966365f991fd
            status: offline
          createdAt: '2017-01-16T10:36:46.390569'
          description: Device
          displayName: ThingsPro
          mac: 223344FF8F11
          iccId: 898600MFSSYYGXXXXXXA
          serialNumber: MOXA00000002
          properties:
            aliasName: ThingsPro
            createdAt: '2017-03-09T05:38:58.925514'
            deviceUUID: 2730e69e-8d5a-4642-a7cf-966365f991fd
            gps:
              lat: 0
              lng: 0
          updatedAt: '2017-03-20T06:32:35.814447'
          uuid: 2730e69e-8d5a-4642-a7cf-966365f991fd
        - connection:
            createdAt: '2017-03-08T15:54:59.782570'
            deviceUUID: 6292ca47-f69b-4399-8bdc-3011dc5142df
            status: created
          createdAt: '2017-03-08T15:54:59.782570'
          description: Device
          displayName: Dummy device
          mac: 223344FF8F54
          iccId: 898600MFSSYYGXXXXXXB
          serialNumber: MOXA00000003
          properties: {}
          updatedAt: '2017-03-08T15:54:59.782570'
          uuid: 6292ca47-f69b-4399-8bdc-3011dc5142df
      limit: 20
      offset: 0
    FilterDevice:
      {
        "offset": 0,
        "limit": 100,
        "keys": {
          "serialNumber": {
            "filter": "MOXA00000003"
          },
          "uuid": {
            "filter": "6292ca47-f69b-4399-8bdc-3011dc5142df"
          },
          "mac": {
            "filter": "223344FF8F54"
          },
          "displayName": {
            "filter": "DEVICE_NAME"
          },
          "defaultRoute": {
            "filter": "eth0"
          },
          "softwareVersion": {
            "filter": "2.1"
          }
        }
      }
